/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "shortcutsprefs.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *page;
  GtkWidget *hbox9;
  GtkWidget *label64;
  GtkWidget *seach;
  GtkWidget *scrolledwindow;
  GtkWidget *treeview;
  GtkWidget *shortcut_frame;
  GtkWidget *alignment29;
  GtkWidget *vbox11;
  GtkWidget *hbox10;
  GtkWidget *shortcut_none;
  GSList *shortcut_none_group = NULL;
  GtkWidget *shortcut_default;
  GtkWidget *shortcut_custom;
  GtkWidget *shortcut;
  GtkWidget *hbox11;
  GtkWidget *label66;
  GtkWidget *default_label;
  GtkWidget *label65;

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);

  page = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (page);
  gtk_container_add (GTK_CONTAINER (window), page);
  gtk_container_set_border_width (GTK_CONTAINER (page), 3);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_box_pack_start (GTK_BOX (page), hbox9, FALSE, FALSE, 0);

  label64 = gtk_label_new (_("Search: "));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox9), label64, FALSE, FALSE, 0);

  seach = gtk_entry_new ();
  gtk_widget_show (seach);
  gtk_box_pack_start (GTK_BOX (hbox9), seach, TRUE, TRUE, 0);

  scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow);
  gtk_box_pack_start (GTK_BOX (page), scrolledwindow, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow), GTK_SHADOW_IN);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow), treeview);
  GTK_WIDGET_SET_FLAGS (treeview, GTK_CAN_DEFAULT);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview), TRUE);

  shortcut_frame = gtk_frame_new (NULL);
  gtk_widget_show (shortcut_frame);
  gtk_box_pack_start (GTK_BOX (page), shortcut_frame, FALSE, FALSE, 0);

  alignment29 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (shortcut_frame), alignment29);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment29), 3, 3, 3, 3);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (alignment29), vbox11);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox10, TRUE, TRUE, 0);

  shortcut_none = gtk_radio_button_new_with_mnemonic (NULL, _("None "));
  gtk_widget_show (shortcut_none);
  gtk_box_pack_start (GTK_BOX (hbox10), shortcut_none, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (shortcut_none), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (shortcut_none), shortcut_none_group);
  shortcut_none_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (shortcut_none));

  shortcut_default = gtk_radio_button_new_with_mnemonic (NULL, _("Default "));
  gtk_widget_show (shortcut_default);
  gtk_box_pack_start (GTK_BOX (hbox10), shortcut_default, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (shortcut_default), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (shortcut_default), shortcut_none_group);
  shortcut_none_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (shortcut_default));

  shortcut_custom = gtk_radio_button_new_with_mnemonic (NULL, _("Custom "));
  gtk_widget_show (shortcut_custom);
  gtk_box_pack_start (GTK_BOX (hbox10), shortcut_custom, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (shortcut_custom), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (shortcut_custom), shortcut_none_group);
  shortcut_none_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (shortcut_custom));

  shortcut = gtk_button_new_with_mnemonic ("");
  gtk_widget_show (shortcut);
  gtk_box_pack_start (GTK_BOX (hbox10), shortcut, TRUE, TRUE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (shortcut), FALSE);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox11, TRUE, TRUE, 0);

  label66 = gtk_label_new (_(" Default key: "));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox11), label66, FALSE, FALSE, 0);

  default_label = gtk_label_new ("");
  gtk_widget_show (default_label);
  gtk_box_pack_start (GTK_BOX (hbox11), default_label, FALSE, FALSE, 0);

  label65 = gtk_label_new (_("Shortcut for selected action"));
  gtk_widget_show (label65);
  gtk_frame_set_label_widget (GTK_FRAME (shortcut_frame), label65);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, page, "page");
  GLADE_HOOKUP_OBJECT (window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window, label64, "label64");
  GLADE_HOOKUP_OBJECT (window, seach, "seach");
  GLADE_HOOKUP_OBJECT (window, scrolledwindow, "scrolledwindow");
  GLADE_HOOKUP_OBJECT (window, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (window, shortcut_frame, "shortcut_frame");
  GLADE_HOOKUP_OBJECT (window, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window, shortcut_none, "shortcut_none");
  GLADE_HOOKUP_OBJECT (window, shortcut_default, "shortcut_default");
  GLADE_HOOKUP_OBJECT (window, shortcut_custom, "shortcut_custom");
  GLADE_HOOKUP_OBJECT (window, shortcut, "shortcut");
  GLADE_HOOKUP_OBJECT (window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window, label66, "label66");
  GLADE_HOOKUP_OBJECT (window, default_label, "default_label");
  GLADE_HOOKUP_OBJECT (window, label65, "label65");

  gtk_widget_grab_focus (treeview);
  return window;
}

GtkWidget*
create_dialog (void)
{
  GtkWidget *dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *frame1;
  GtkWidget *alignment30;
  GtkWidget *page;
  GtkWidget *dialog_action_area1;
  GtkWidget *reset;
  GtkWidget *alignment31;
  GtkWidget *hbox12;
  GtkWidget *image1;
  GtkWidget *label67;
  GtkWidget *cancel;
  GtkWidget *ok;

  dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog), _("Configure Shortcuts"));
  gtk_window_set_default_size (GTK_WINDOW (dialog), -1, 350);
  gtk_window_set_type_hint (GTK_WINDOW (dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), frame1, TRUE, TRUE, 0);

  alignment30 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (frame1), alignment30);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment30), 3, 3, 3, 3);

  page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (page);
  gtk_container_add (GTK_CONTAINER (alignment30), page);

  dialog_action_area1 = GTK_DIALOG (dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  reset = gtk_button_new ();
  gtk_widget_show (reset);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), reset, GTK_RESPONSE_REJECT);
  GTK_WIDGET_SET_FLAGS (reset, GTK_CAN_DEFAULT);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (reset), alignment31);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox12);

  image1 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox12), image1, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("Set _Defaults"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox12), label67, FALSE, FALSE, 0);

  cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (cancel), FALSE);

  ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (ok), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog, "dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (dialog, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (dialog, page, "page");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog, reset, "reset");
  GLADE_HOOKUP_OBJECT (dialog, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (dialog, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (dialog, image1, "image1");
  GLADE_HOOKUP_OBJECT (dialog, label67, "label67");
  GLADE_HOOKUP_OBJECT (dialog, cancel, "cancel");
  GLADE_HOOKUP_OBJECT (dialog, ok, "ok");

  gtk_widget_grab_default (ok);
  return dialog;
}

