#!/bin/sh

if [ -z $CYGWIN_BIN_DIR ]; then
    CYGWIN_BIN_DIR=/opt/cygwin/bin
fi

TARGET=i686-pc-cygwin

export PATH=/opt/cygwin/i686-pc-cygwin/bin:/opt/cygwin/bin:$PATH

export ADDR2LINE="$CYGWIN_BIN_DIR/$TARGET-addr2line"
export AR="$CYGWIN_BIN_DIR/$TARGET-ar"
export AS="$CYGWIN_BIN_DIR/$TARGET-as"
export CC="$CYGWIN_BIN_DIR/$TARGET-gcc"
export CPP="$CYGWIN_BIN_DIR/$TARGET-cpp"
export CPPFILT="$CYGWIN_BIN_DIR/$TARGET-c++filt"
export CXX="$CYGWIN_BIN_DIR/$TARGET-g++"
export DLLTOOL="$CYGWIN_BIN_DIR/$TARGET-dlltool"
export DLLWRAP="$CYGWIN_BIN_DIR/$TARGET-dllwrap"
export GCOV="$CYGWIN_BIN_DIR/$TARGET-gcov"
export LD="$CYGWIN_BIN_DIR/$TARGET-ld"
export NM="$CYGWIN_BIN_DIR/$TARGET-nm"
export OBJCOPY="$CYGWIN_BIN_DIR/$TARGET-objcopy"
export OBJDUMP="$CYGWIN_BIN_DIR/$TARGET-objdump"
export RANLIB="$CYGWIN_BIN_DIR/$TARGET-ranlib"
export READELF="$CYGWIN_BIN_DIR/$TARGET-readelf"
export SIZE="$CYGWIN_BIN_DIR/$TARGET-size"
export STRINGS="$CYGWIN_BIN_DIR/$TARGET-strings"
export STRIP="$CYGWIN_BIN_DIR/$TARGET-strip"
export WINDRES="$CYGWIN_BIN_DIR/$TARGET-windres"

export CFLAGS="${CFLAGS:-"-O2 -g"} -mms-bitfields -march=i686"
export CXXFLAGS="${CFLAGS:-"-O2 -g"} -mms-bitfields -march=i686"

if [ "x$CONFIGURE" = "x" ]; then
    CONFIGURE="configure"
    if [ ! -e $CONFIGURE ]; then
        CONFIGURE=`dirname $0`/configure
    fi
    if [ ! -e $CONFIGURE ]; then
        echo "Can't find configure script"
        exit 1
    fi
fi

sh $CONFIGURE --target=$TARGET --host=$TARGET $*
exit $?
