#ifdef DUMMY_POSIX
#define _moo_lua_dummy_function_which_does_nothing_but_is_needed_to_shut_up_the_linker _moo_lua_dummy_function_which_does_nothing_but_is_needed_to_shut_up_the_linker_posix
#else
#define _moo_lua_dummy_function_which_does_nothing_but_is_needed_to_shut_up_the_linker _moo_lua_dummy_function_which_does_nothing_but_is_needed_to_shut_up_the_linker_win32
#endif

void _moo_lua_dummy_function_which_does_nothing_but_is_needed_to_shut_up_the_linker (void);
void _moo_lua_dummy_function_which_does_nothing_but_is_needed_to_shut_up_the_linker (void)
{
}
