/*
 *   moocppg-gtk.h
 *
 *   Copyright (C) 2004-2009 by Yevgen Muntyan <muntyan@tamu.edu>
 *
 *   This file is part of medit.  medit is free software; you can
 *   redistribute it and/or modify it under the terms of the
 *   GNU Lesser General Public License as published by the
 *   Free Software Foundation; either version 2.1 of the License,
 *   or (at your option) any later version.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with medit.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef MOO_CPP_GTK_H
#define MOO_CPP_GTK_H

#include <mooutils/moocpp-gobject.h>
#include <gtk/gtk.h>

namespace moo {

#define _MOO_DEFINE_GTK_PROXY_CLASS(Name, Parent, NAME)     \
    namespace Gtk {                                         \
    MOO_DEFINE_GOBJECT_PROXY_CLASS(Name, Parent,            \
                                   Gtk##Name,               \
                                   GTK_TYPE_##NAME);        \
    }                                                       \
    MOO_DEFINE_GOBJECT_HELPER_CLASS(Gtk::Name, Gtk##Name)

#define MOO_DEFINE_GTK_PROXY_CLASS(Name, Parent, NAME) _MOO_DEFINE_GTK_PROXY_CLASS(Name, Parent, NAME)
#define MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(Name, NAME) _MOO_DEFINE_GTK_PROXY_CLASS(Name, G::Object, NAME)

MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(Object, OBJECT);
MOO_DEFINE_GTK_PROXY_CLASS(Widget, Object, WIDGET);
MOO_DEFINE_GTK_PROXY_CLASS(Container, Widget, CONTAINER);
MOO_DEFINE_GTK_PROXY_CLASS(Bin, Container, BIN);
MOO_DEFINE_GTK_PROXY_CLASS(Window, Bin, WINDOW);
MOO_DEFINE_GTK_PROXY_CLASS(Dialog, Window, DIALOG);
MOO_DEFINE_GTK_PROXY_CLASS(AboutDialog, Dialog, ABOUT_DIALOG);
MOO_DEFINE_GTK_PROXY_CLASS(FileChooserDialog, Dialog, FILE_CHOOSER_DIALOG);
MOO_DEFINE_GTK_PROXY_CLASS(FontSelectionDialog, Dialog, FONT_SELECTION_DIALOG);
MOO_DEFINE_GTK_PROXY_CLASS(MessageDialog, Dialog, MESSAGE_DIALOG);
MOO_DEFINE_GTK_PROXY_CLASS(Button, Bin, BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(ToggleButton, Button, TOGGLE_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(CheckButton, ToggleButton, CHECK_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(RadioButton, CheckButton, RADIO_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(ColorButton, Button, COLOR_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(FontButton, Button, FONT_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(Item, Bin, ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(MenuItem, Item, MENU_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(CheckMenuItem, MenuItem, CHECK_MENU_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(RadioMenuItem, CheckMenuItem, RADIO_MENU_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(ImageMenuItem, MenuItem, IMAGE_MENU_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(SeparatorMenuItem, MenuItem, SEPARATOR_MENU_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(ComboBox, Bin, COMBO_BOX);
MOO_DEFINE_GTK_PROXY_CLASS(ComboBoxEntry, ComboBox, COMBO_BOX_ENTRY);
MOO_DEFINE_GTK_PROXY_CLASS(EventBox, Bin, EVENT_BOX);
MOO_DEFINE_GTK_PROXY_CLASS(Expander, Bin, EXPANDER);
MOO_DEFINE_GTK_PROXY_CLASS(ToolItem, Bin, TOOL_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(ToolButton, ToolItem, TOOL_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(MenuToolButton, ToolButton, MENU_TOOL_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(ToggleToolButton, ToolButton, TOGGLE_TOOL_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(RadioToolButton, ToggleToolButton, RADIO_TOOL_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(SeparatorToolItem, ToolItem, SEPARATOR_TOOL_ITEM);
MOO_DEFINE_GTK_PROXY_CLASS(ScrolledWindow, Bin, SCROLLED_WINDOW);
MOO_DEFINE_GTK_PROXY_CLASS(Viewport, Bin, VIEWPORT);
MOO_DEFINE_GTK_PROXY_CLASS(Box, Container, BOX);
MOO_DEFINE_GTK_PROXY_CLASS(ButtonBox, Box, BUTTON_BOX);
MOO_DEFINE_GTK_PROXY_CLASS(HButtonBox, ButtonBox, HBUTTON_BOX);
MOO_DEFINE_GTK_PROXY_CLASS(VButtonBox, ButtonBox, VBUTTON_BOX);
MOO_DEFINE_GTK_PROXY_CLASS(VBox, Box, VBOX);
MOO_DEFINE_GTK_PROXY_CLASS(HBox, Box, HBOX);
MOO_DEFINE_GTK_PROXY_CLASS(Statusbar, HBox, STATUSBAR);
MOO_DEFINE_GTK_PROXY_CLASS(Paned, Container, PANED);
MOO_DEFINE_GTK_PROXY_CLASS(HPaned, Paned, HPANED);
MOO_DEFINE_GTK_PROXY_CLASS(VPaned, Paned, VPANED);
MOO_DEFINE_GTK_PROXY_CLASS(IconView, Container, ICON_VIEW);
MOO_DEFINE_GTK_PROXY_CLASS(MenuShell, Container, MENU_SHELL);
MOO_DEFINE_GTK_PROXY_CLASS(MenuBar, MenuShell, MENU_BAR);
MOO_DEFINE_GTK_PROXY_CLASS(Menu, MenuShell, MENU);
MOO_DEFINE_GTK_PROXY_CLASS(Notebook, Container, NOTEBOOK);
MOO_DEFINE_GTK_PROXY_CLASS(Table, Container, TABLE);
MOO_DEFINE_GTK_PROXY_CLASS(TextView, Container, TEXT_VIEW);
MOO_DEFINE_GTK_PROXY_CLASS(Toolbar, Container, TOOLBAR);
MOO_DEFINE_GTK_PROXY_CLASS(TreeView, Container, TREE_VIEW);
MOO_DEFINE_GTK_PROXY_CLASS(Misc, Widget, MISC);
MOO_DEFINE_GTK_PROXY_CLASS(Label, Misc, LABEL);
MOO_DEFINE_GTK_PROXY_CLASS(AccelLabel, Label, ACCEL_LABEL);
MOO_DEFINE_GTK_PROXY_CLASS(Image, Misc, IMAGE);
MOO_DEFINE_GTK_PROXY_CLASS(Calendar, Widget, CALENDAR);
MOO_DEFINE_GTK_PROXY_CLASS(CellView, Widget, CELL_VIEW);
MOO_DEFINE_GTK_PROXY_CLASS(DrawingArea, Widget, DRAWING_AREA);
MOO_DEFINE_GTK_PROXY_CLASS(Entry, Widget, ENTRY);
MOO_DEFINE_GTK_PROXY_CLASS(SpinButton, Entry, SPIN_BUTTON);
MOO_DEFINE_GTK_PROXY_CLASS(Range, Widget, RANGE);
MOO_DEFINE_GTK_PROXY_CLASS(Scale, Range, SCALE);
MOO_DEFINE_GTK_PROXY_CLASS(HScale, Scale, HSCALE);
MOO_DEFINE_GTK_PROXY_CLASS(VScale, Scale, VSCALE);
MOO_DEFINE_GTK_PROXY_CLASS(Scrollbar, Range, SCROLLBAR);
MOO_DEFINE_GTK_PROXY_CLASS(HScrollbar, Scrollbar, HSCROLLBAR);
MOO_DEFINE_GTK_PROXY_CLASS(VScrollbar, Scrollbar, VSCROLLBAR);
MOO_DEFINE_GTK_PROXY_CLASS(Separator, Widget, SEPARATOR);
MOO_DEFINE_GTK_PROXY_CLASS(HSeparator, Widget, HSEPARATOR);
MOO_DEFINE_GTK_PROXY_CLASS(VSeparator, Widget, VSEPARATOR);
MOO_DEFINE_GTK_PROXY_CLASS(Progress, Widget, PROGRESS);
MOO_DEFINE_GTK_PROXY_CLASS(ProgressBar, Progress, PROGRESS_BAR);
MOO_DEFINE_GTK_PROXY_CLASS(Adjustment, Object, ADJUSTMENT);
MOO_DEFINE_GTK_PROXY_CLASS(CellRenderer, Object, CELL_RENDERER);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererText, CellRenderer, CELL_RENDERER_TEXT);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererAccel, CellRendererText, CELL_RENDERER_ACCEL);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererCombo, CellRendererText, CELL_RENDERER_COMBO);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererSpin, CellRendererText, CELL_RENDERER_SPIN);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererPixbuf, CellRenderer, CELL_RENDERER_PIXBUF);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererProgress, CellRenderer, CELL_RENDERER_PROGRESS);
MOO_DEFINE_GTK_PROXY_CLASS(CellRendererToggle, CellRenderer, CELL_RENDERER_TOGGLE);
MOO_DEFINE_GTK_PROXY_CLASS(FileFilter, Object, FILE_FILTER);
MOO_DEFINE_GTK_PROXY_CLASS(ItemFactory, Object, ITEM_FACTORY);
MOO_DEFINE_GTK_PROXY_CLASS(TreeViewColumn, Object, TREE_VIEW_COLUMN);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(AccelGroup, ACCEL_GROUP);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(AccelMap, ACCEL_MAP);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(Action, ACTION);
MOO_DEFINE_GTK_PROXY_CLASS(ToggleAction, Action, TOGGLE_ACTION);
MOO_DEFINE_GTK_PROXY_CLASS(RadioAction, ToggleAction, RADIO_ACTION);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(ActionGroup, ACTION_GROUP);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(Clipboard, CLIPBOARD);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(IconTheme, ICON_THEME);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(ListStore, LIST_STORE);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(Settings, SETTINGS);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(Style, STYLE);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TextBuffer, TEXT_BUFFER);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TextChildAnchor, TEXT_CHILD_ANCHOR);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TextMark, TEXT_MARK);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TextTag, TEXT_TAG);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TextTagTable, TEXT_TAG_TABLE);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TreeModelFilter, TREE_MODEL_FILTER);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TreeModelSort, TREE_MODEL_SORT);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TreeSelection, TREE_SELECTION);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(TreeStore, TREE_STORE);
MOO_DEFINE_GTK_PROXY_CLASS_GOBJ(WindowGroup, WINDOW_GROUP);

#undef MOO_DEFINE_GTK_PROXY_CLASS
#undef MOO_DEFINE_GTK_PROXY_CLASS_GOBJ

} // namespace moo

#endif /* MOO_CPP_GOBJECT_H */
/* -%- strip:true -%- */
