#
#   moo/mooedit/glade/Makefile.incl
#

mooedit_glade = $(mooedit)/glade

moo_extra_dist +=                             \
    $(mooedit_glade)/statusbar.glade          \
    $(mooedit_glade)/quicksearch.glade        \
    $(mooedit_glade)/mootextgotoline.glade    \
    $(mooedit_glade)/mootextfind.glade        \
    $(mooedit_glade)/mooeditprefs.glade       \
    $(mooedit_glade)/mooeditsavemult.glade    \
    $(mooedit_glade)/moopluginprefs.glade     \
    $(mooedit_glade)/mooprint.glade
