/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "mooeditprefs.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window (void)
{
  GtkWidget *window;
  GtkWidget *notebook;
  GtkWidget *vbox3;
  GtkWidget *frame15;
  GtkWidget *alignment25;
  GtkWidget *vbox9;
  GtkWidget *smarthome;
  GtkWidget *hbox1;
  GtkWidget *label32;
  GtkObject *tabswidth_spin_adj;
  GtkWidget *tabswidth_spin;
  GtkWidget *usespaces;
  GtkWidget *label64;
  GtkWidget *frame16;
  GtkWidget *alignment26;
  GtkWidget *vbox10;
  GtkWidget *autoindent;
  GtkWidget *tab_indents;
  GtkWidget *backspace_indents;
  GtkWidget *label66;
  GtkWidget *frame17;
  GtkWidget *alignment27;
  GtkWidget *vbox11;
  GtkWidget *hbox6;
  GtkWidget *limit_undo;
  GtkObject *limit_undo_spin_adj;
  GtkWidget *limit_undo_spin;
  GtkWidget *limit_undo_actions_label;
  GtkWidget *label67;
  GtkWidget *frame25;
  GtkWidget *alignment37;
  GtkWidget *vbox19;
  GtkWidget *hbox11;
  GtkWidget *auto_save;
  GtkObject *auto_save_interval_adj;
  GtkWidget *auto_save_interval;
  GtkWidget *auto_save_label;
  GtkWidget *label95;
  GtkWidget *label21;
  GtkWidget *vbox12;
  GtkWidget *frame18;
  GtkWidget *alignment28;
  GtkWidget *vbox13;
  GtkWidget *enable_wrapping;
  GtkWidget *dont_split_words;
  GtkWidget *label70;
  GtkWidget *frame19;
  GtkWidget *alignment29;
  GtkWidget *vbox14;
  GtkWidget *show_line_numbers;
  GtkWidget *hbox10;
  GtkWidget *show_right_margin;
  GtkObject *show_right_margin_spin_adj;
  GtkWidget *show_right_margin_spin;
  GtkWidget *label73;
  GtkWidget *frame26;
  GtkWidget *alignment38;
  GtkWidget *vbox20;
  GtkWidget *bracket_styles_notebook;
  GtkWidget *vbox21;
  GtkWidget *alignment40;
  GtkWidget *table13;
  GtkWidget *bracket_correct_foreground;
  GtkWidget *bracket_correct_background;
  GtkWidget *bracket_correct_use_foreground;
  GtkWidget *bracket_correct_use_background;
  GtkWidget *bracket_correct_italic;
  GtkWidget *image6;
  GtkWidget *bracket_correct_strikethrough;
  GtkWidget *image8;
  GtkWidget *bracket_correct_underline;
  GtkWidget *image7;
  GtkWidget *bracket_correct_bold;
  GtkWidget *image_9;
  GtkWidget *label99;
  GtkWidget *vbox22;
  GtkWidget *alignment41;
  GtkWidget *table14;
  GtkWidget *bracket_incorrect_foreground;
  GtkWidget *bracket_incorrect_background;
  GtkWidget *bracket_incorrect_use_foreground;
  GtkWidget *bracket_incorrect_use_background;
  GtkWidget *bracket_incorrect_italic;
  GtkWidget *image10;
  GtkWidget *bracket_incorrect_strikethrough;
  GtkWidget *image12;
  GtkWidget *bracket_incorrect_bold;
  GtkWidget *image9;
  GtkWidget *bracket_incorrect_underline;
  GtkWidget *image11;
  GtkWidget *label100;
  GtkWidget *check_brackets;
  GtkWidget *label62;
  GtkWidget *vbox15;
  GtkWidget *frame20;
  GtkWidget *alignment30;
  GtkWidget *vbox16;
  GtkWidget *use_default_font;
  GtkWidget *font_hbox;
  GtkWidget *label79;
  GtkWidget *font;
  GtkWidget *label78;
  GtkWidget *frame21;
  GtkWidget *alignment31;
  GtkWidget *vbox17;
  GtkWidget *use_default_colors;
  GtkWidget *text_colors_table;
  GtkWidget *label82;
  GtkWidget *label83;
  GtkWidget *text_color;
  GtkWidget *text_background_color;
  GtkWidget *label84;
  GtkWidget *label85;
  GtkWidget *selected_text_color;
  GtkWidget *selection_color;
  GtkWidget *label81;
  GtkWidget *frame22;
  GtkWidget *alignment32;
  GtkWidget *vbox18;
  GtkWidget *highlight_current_line;
  GtkWidget *highlight_current_line_color;
  GtkWidget *label90;
  GtkWidget *label61;
  GtkWidget *frame23;
  GtkWidget *alignment33;
  GtkWidget *syntax_highlighting_vbox;
  GtkWidget *hbox7;
  GtkWidget *label93;
  GtkWidget *language_combo;
  GtkWidget *frame24;
  GtkWidget *alignment34;
  GtkWidget *hbox8;
  GtkWidget *scrolledwindow1;
  GtkWidget *styles_list;
  GtkWidget *style_vbox;
  GtkWidget *alignment35;
  GtkWidget *hbox9;
  GtkWidget *bold;
  GtkWidget *image1;
  GtkWidget *italic;
  GtkWidget *image2;
  GtkWidget *underline;
  GtkWidget *image3;
  GtkWidget *strikethrough;
  GtkWidget *image4;
  GtkWidget *alignment36;
  GtkWidget *table12;
  GtkWidget *foreground_color;
  GtkWidget *background_color;
  GtkWidget *foreground_toggle;
  GtkWidget *background_toggle;
  GtkWidget *use_syntax_highlighting;
  GtkWidget *label92;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window), _("window"));

  notebook = gtk_notebook_new ();
  gtk_widget_show (notebook);
  gtk_container_add (GTK_CONTAINER (window), notebook);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook), vbox3);

  frame15 = gtk_frame_new (NULL);
  gtk_widget_show (frame15);
  gtk_box_pack_start (GTK_BOX (vbox3), frame15, FALSE, FALSE, 0);

  alignment25 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (frame15), alignment25);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment25), 0, 3, 3, 3);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (alignment25), vbox9);

  smarthome = gtk_check_button_new_with_mnemonic (_("Smart Home and End"));
  gtk_widget_show (smarthome);
  gtk_box_pack_start (GTK_BOX (vbox9), smarthome, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (smarthome), FALSE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox1, FALSE, FALSE, 0);

  label32 = gtk_label_new (_("Tabs Width: "));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox1), label32, FALSE, FALSE, 0);

  tabswidth_spin_adj = gtk_adjustment_new (6, 1, 100, 1, 10, 10);
  tabswidth_spin = gtk_spin_button_new (GTK_ADJUSTMENT (tabswidth_spin_adj), 1, 0);
  gtk_widget_show (tabswidth_spin);
  gtk_box_pack_start (GTK_BOX (hbox1), tabswidth_spin, FALSE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (tabswidth_spin), TRUE);

  usespaces = gtk_check_button_new_with_mnemonic (_("Use Spaces Instead of Tabs"));
  gtk_widget_show (usespaces);
  gtk_box_pack_start (GTK_BOX (vbox9), usespaces, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (usespaces), FALSE);

  label64 = gtk_label_new (_("Editing"));
  gtk_widget_show (label64);
  gtk_frame_set_label_widget (GTK_FRAME (frame15), label64);

  frame16 = gtk_frame_new (NULL);
  gtk_widget_show (frame16);
  gtk_box_pack_start (GTK_BOX (vbox3), frame16, FALSE, FALSE, 0);

  alignment26 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (frame16), alignment26);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment26), 0, 3, 3, 3);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (alignment26), vbox10);

  autoindent = gtk_check_button_new_with_mnemonic (_("Auto indent"));
  gtk_widget_show (autoindent);
  gtk_box_pack_start (GTK_BOX (vbox10), autoindent, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (autoindent), FALSE);

  tab_indents = gtk_check_button_new_with_mnemonic (_("Tab key indents"));
  gtk_widget_show (tab_indents);
  gtk_box_pack_start (GTK_BOX (vbox10), tab_indents, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (tab_indents, FALSE);
  gtk_button_set_focus_on_click (GTK_BUTTON (tab_indents), FALSE);

  backspace_indents = gtk_check_button_new_with_mnemonic (_("Backspace key indents"));
  gtk_widget_show (backspace_indents);
  gtk_box_pack_start (GTK_BOX (vbox10), backspace_indents, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (backspace_indents, FALSE);
  gtk_button_set_focus_on_click (GTK_BUTTON (backspace_indents), FALSE);

  label66 = gtk_label_new (_("Indentation"));
  gtk_widget_show (label66);
  gtk_frame_set_label_widget (GTK_FRAME (frame16), label66);

  frame17 = gtk_frame_new (NULL);
  gtk_widget_show (frame17);
  gtk_box_pack_start (GTK_BOX (vbox3), frame17, FALSE, FALSE, 0);

  alignment27 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (frame17), alignment27);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment27), 0, 3, 3, 3);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (alignment27), vbox11);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox6, FALSE, FALSE, 0);

  limit_undo = gtk_check_button_new_with_mnemonic (_("Limit undo to "));
  gtk_widget_show (limit_undo);
  gtk_box_pack_start (GTK_BOX (hbox6), limit_undo, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (limit_undo), FALSE);

  limit_undo_spin_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  limit_undo_spin = gtk_spin_button_new (GTK_ADJUSTMENT (limit_undo_spin_adj), 1, 0);
  gtk_widget_show (limit_undo_spin);
  gtk_box_pack_start (GTK_BOX (hbox6), limit_undo_spin, FALSE, FALSE, 0);

  limit_undo_actions_label = gtk_label_new (_(" actions"));
  gtk_widget_show (limit_undo_actions_label);
  gtk_box_pack_start (GTK_BOX (hbox6), limit_undo_actions_label, FALSE, FALSE, 0);

  label67 = gtk_label_new (_("Undo"));
  gtk_widget_show (label67);
  gtk_frame_set_label_widget (GTK_FRAME (frame17), label67);

  frame25 = gtk_frame_new (NULL);
  gtk_widget_show (frame25);
  gtk_box_pack_start (GTK_BOX (vbox3), frame25, FALSE, FALSE, 0);

  alignment37 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (frame25), alignment37);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment37), 0, 3, 3, 3);

  vbox19 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox19);
  gtk_container_add (GTK_CONTAINER (alignment37), vbox19);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox19), hbox11, FALSE, FALSE, 0);

  auto_save = gtk_check_button_new_with_mnemonic (_("Auto save every "));
  gtk_widget_show (auto_save);
  gtk_box_pack_start (GTK_BOX (hbox11), auto_save, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (auto_save), FALSE);

  auto_save_interval_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  auto_save_interval = gtk_spin_button_new (GTK_ADJUSTMENT (auto_save_interval_adj), 1, 0);
  gtk_widget_show (auto_save_interval);
  gtk_box_pack_start (GTK_BOX (hbox11), auto_save_interval, FALSE, FALSE, 0);

  auto_save_label = gtk_label_new (_(" minutes"));
  gtk_widget_show (auto_save_label);
  gtk_box_pack_start (GTK_BOX (hbox11), auto_save_label, FALSE, FALSE, 0);

  label95 = gtk_label_new (_("Auto Save"));
  gtk_widget_show (label95);
  gtk_frame_set_label_widget (GTK_FRAME (frame25), label95);

  label21 = gtk_label_new (_("General"));
  gtk_widget_show (label21);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), label21);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (notebook), vbox12);

  frame18 = gtk_frame_new (NULL);
  gtk_widget_show (frame18);
  gtk_box_pack_start (GTK_BOX (vbox12), frame18, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame18), 3);

  alignment28 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (frame18), alignment28);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment28), 0, 3, 3, 3);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_container_add (GTK_CONTAINER (alignment28), vbox13);

  enable_wrapping = gtk_check_button_new_with_mnemonic (_("Enable text wrapping"));
  gtk_widget_show (enable_wrapping);
  gtk_box_pack_start (GTK_BOX (vbox13), enable_wrapping, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (enable_wrapping), FALSE);

  dont_split_words = gtk_check_button_new_with_mnemonic (_("Do not split words"));
  gtk_widget_show (dont_split_words);
  gtk_box_pack_start (GTK_BOX (vbox13), dont_split_words, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (dont_split_words), FALSE);

  label70 = gtk_label_new (_("Text wrapping"));
  gtk_widget_show (label70);
  gtk_frame_set_label_widget (GTK_FRAME (frame18), label70);

  frame19 = gtk_frame_new (NULL);
  gtk_widget_show (frame19);
  gtk_box_pack_start (GTK_BOX (vbox12), frame19, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame19), 3);

  alignment29 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (frame19), alignment29);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment29), 0, 3, 3, 3);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_container_add (GTK_CONTAINER (alignment29), vbox14);

  show_line_numbers = gtk_check_button_new_with_mnemonic (_("Show line numbers"));
  gtk_widget_show (show_line_numbers);
  gtk_box_pack_start (GTK_BOX (vbox14), show_line_numbers, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (show_line_numbers), FALSE);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox10, TRUE, TRUE, 0);

  show_right_margin = gtk_check_button_new_with_mnemonic (_("Show right margin at column "));
  gtk_widget_show (show_right_margin);
  gtk_box_pack_start (GTK_BOX (hbox10), show_right_margin, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (show_right_margin), FALSE);

  show_right_margin_spin_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  show_right_margin_spin = gtk_spin_button_new (GTK_ADJUSTMENT (show_right_margin_spin_adj), 1, 0);
  gtk_widget_show (show_right_margin_spin);
  gtk_box_pack_start (GTK_BOX (hbox10), show_right_margin_spin, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (show_right_margin_spin), TRUE);

  label73 = gtk_label_new (_("Misc"));
  gtk_widget_show (label73);
  gtk_frame_set_label_widget (GTK_FRAME (frame19), label73);

  frame26 = gtk_frame_new (NULL);
  gtk_widget_show (frame26);
  gtk_box_pack_start (GTK_BOX (vbox12), frame26, FALSE, FALSE, 0);

  alignment38 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (frame26), alignment38);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment38), 0, 3, 3, 3);

  vbox20 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox20);
  gtk_container_add (GTK_CONTAINER (alignment38), vbox20);

  bracket_styles_notebook = gtk_notebook_new ();
  gtk_widget_show (bracket_styles_notebook);
  gtk_box_pack_start (GTK_BOX (vbox20), bracket_styles_notebook, FALSE, FALSE, 0);

  vbox21 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox21);
  gtk_container_add (GTK_CONTAINER (bracket_styles_notebook), vbox21);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (bracket_styles_notebook), vbox21,
                                      FALSE, FALSE, GTK_PACK_START);

  alignment40 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment40);
  gtk_box_pack_start (GTK_BOX (vbox21), alignment40, FALSE, FALSE, 0);

  table13 = gtk_table_new (2, 4, FALSE);
  gtk_widget_show (table13);
  gtk_container_add (GTK_CONTAINER (alignment40), table13);

  bracket_correct_foreground = gtk_color_button_new ();
  gtk_widget_show (bracket_correct_foreground);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_foreground, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_foreground), FALSE);

  bracket_correct_background = gtk_color_button_new ();
  gtk_widget_show (bracket_correct_background);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_background, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_background), FALSE);

  bracket_correct_use_foreground = gtk_check_button_new_with_mnemonic (_("Foreground: "));
  gtk_widget_show (bracket_correct_use_foreground);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_use_foreground, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_use_foreground), FALSE);

  bracket_correct_use_background = gtk_check_button_new_with_mnemonic (_("Background: "));
  gtk_widget_show (bracket_correct_use_background);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_use_background, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_use_background), FALSE);

  bracket_correct_italic = gtk_toggle_button_new ();
  gtk_widget_show (bracket_correct_italic);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_italic, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_correct_italic), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_italic), FALSE);

  image6 = gtk_image_new_from_stock ("gtk-italic", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (bracket_correct_italic), image6);

  bracket_correct_strikethrough = gtk_toggle_button_new ();
  gtk_widget_show (bracket_correct_strikethrough);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_strikethrough, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_correct_strikethrough), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_strikethrough), FALSE);

  image8 = gtk_image_new_from_stock ("gtk-strikethrough", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (bracket_correct_strikethrough), image8);

  bracket_correct_underline = gtk_toggle_button_new ();
  gtk_widget_show (bracket_correct_underline);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_underline, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_correct_underline), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_underline), FALSE);

  image7 = gtk_image_new_from_stock ("gtk-underline", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (bracket_correct_underline), image7);

  bracket_correct_bold = gtk_toggle_button_new ();
  gtk_widget_show (bracket_correct_bold);
  gtk_table_attach (GTK_TABLE (table13), bracket_correct_bold, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 12, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_correct_bold), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_correct_bold), FALSE);

  image_9 = gtk_image_new_from_stock ("gtk-bold", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image_9);
  gtk_container_add (GTK_CONTAINER (bracket_correct_bold), image_9);

  label99 = gtk_label_new (_("Correct Match"));
  gtk_widget_show (label99);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (bracket_styles_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (bracket_styles_notebook), 0), label99);

  vbox22 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox22);
  gtk_container_add (GTK_CONTAINER (bracket_styles_notebook), vbox22);

  alignment41 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment41);
  gtk_box_pack_start (GTK_BOX (vbox22), alignment41, TRUE, TRUE, 0);

  table14 = gtk_table_new (2, 4, FALSE);
  gtk_widget_show (table14);
  gtk_container_add (GTK_CONTAINER (alignment41), table14);

  bracket_incorrect_foreground = gtk_color_button_new ();
  gtk_widget_show (bracket_incorrect_foreground);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_foreground, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_foreground), FALSE);

  bracket_incorrect_background = gtk_color_button_new ();
  gtk_widget_show (bracket_incorrect_background);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_background, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_background), FALSE);

  bracket_incorrect_use_foreground = gtk_check_button_new_with_mnemonic (_("Foreground: "));
  gtk_widget_show (bracket_incorrect_use_foreground);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_use_foreground, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_use_foreground), FALSE);

  bracket_incorrect_use_background = gtk_check_button_new_with_mnemonic (_("Background: "));
  gtk_widget_show (bracket_incorrect_use_background);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_use_background, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_use_background), FALSE);

  bracket_incorrect_italic = gtk_toggle_button_new ();
  gtk_widget_show (bracket_incorrect_italic);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_italic, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_incorrect_italic), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_italic), FALSE);

  image10 = gtk_image_new_from_stock ("gtk-italic", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (bracket_incorrect_italic), image10);

  bracket_incorrect_strikethrough = gtk_toggle_button_new ();
  gtk_widget_show (bracket_incorrect_strikethrough);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_strikethrough, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_incorrect_strikethrough), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_strikethrough), FALSE);

  image12 = gtk_image_new_from_stock ("gtk-strikethrough", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (bracket_incorrect_strikethrough), image12);

  bracket_incorrect_bold = gtk_toggle_button_new ();
  gtk_widget_show (bracket_incorrect_bold);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_bold, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 12, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_incorrect_bold), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_bold), FALSE);

  image9 = gtk_image_new_from_stock ("gtk-bold", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (bracket_incorrect_bold), image9);

  bracket_incorrect_underline = gtk_toggle_button_new ();
  gtk_widget_show (bracket_incorrect_underline);
  gtk_table_attach (GTK_TABLE (table14), bracket_incorrect_underline, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_relief (GTK_BUTTON (bracket_incorrect_underline), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bracket_incorrect_underline), FALSE);

  image11 = gtk_image_new_from_stock ("gtk-underline", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (bracket_incorrect_underline), image11);

  label100 = gtk_label_new (_("Incorrect Match"));
  gtk_widget_show (label100);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (bracket_styles_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (bracket_styles_notebook), 1), label100);

  check_brackets = gtk_check_button_new_with_mnemonic (_("Highlight matching brackets"));
  gtk_widget_show (check_brackets);
  gtk_frame_set_label_widget (GTK_FRAME (frame26), check_brackets);
  gtk_button_set_focus_on_click (GTK_BUTTON (check_brackets), FALSE);

  label62 = gtk_label_new (_("View"));
  gtk_widget_show (label62);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), label62);

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_container_add (GTK_CONTAINER (notebook), vbox15);

  frame20 = gtk_frame_new (NULL);
  gtk_widget_show (frame20);
  gtk_box_pack_start (GTK_BOX (vbox15), frame20, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame20), 3);

  alignment30 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (frame20), alignment30);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment30), 0, 3, 3, 3);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_container_add (GTK_CONTAINER (alignment30), vbox16);

  use_default_font = gtk_check_button_new_with_mnemonic (_("Use default theme font"));
  gtk_widget_show (use_default_font);
  gtk_box_pack_start (GTK_BOX (vbox16), use_default_font, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (use_default_font), FALSE);

  font_hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (font_hbox);
  gtk_box_pack_start (GTK_BOX (vbox16), font_hbox, TRUE, TRUE, 0);

  label79 = gtk_label_new (_("Editor font: "));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (font_hbox), label79, FALSE, FALSE, 0);

  font = gtk_font_button_new ();
  gtk_widget_show (font);
  gtk_box_pack_start (GTK_BOX (font_hbox), font, TRUE, TRUE, 0);
  gtk_font_button_set_use_font (GTK_FONT_BUTTON (font), TRUE);
  gtk_font_button_set_use_size (GTK_FONT_BUTTON (font), TRUE);
  gtk_button_set_focus_on_click (GTK_BUTTON (font), FALSE);

  label78 = gtk_label_new (_("Font"));
  gtk_widget_show (label78);
  gtk_frame_set_label_widget (GTK_FRAME (frame20), label78);

  frame21 = gtk_frame_new (NULL);
  gtk_widget_show (frame21);
  gtk_box_pack_start (GTK_BOX (vbox15), frame21, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame21), 3);

  alignment31 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (frame21), alignment31);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment31), 0, 3, 3, 3);

  vbox17 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox17);
  gtk_container_add (GTK_CONTAINER (alignment31), vbox17);

  use_default_colors = gtk_check_button_new_with_mnemonic (_("Use default theme colors"));
  gtk_widget_show (use_default_colors);
  gtk_box_pack_start (GTK_BOX (vbox17), use_default_colors, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (use_default_colors), FALSE);

  text_colors_table = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (text_colors_table);
  gtk_box_pack_start (GTK_BOX (vbox17), text_colors_table, TRUE, TRUE, 0);

  label82 = gtk_label_new_with_mnemonic (_("Text color: "));
  gtk_widget_show (label82);
  gtk_table_attach (GTK_TABLE (text_colors_table), label82, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label82), 0, 0.5);

  label83 = gtk_label_new_with_mnemonic (_("Background color: "));
  gtk_widget_show (label83);
  gtk_table_attach (GTK_TABLE (text_colors_table), label83, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label83), 0, 0.5);

  text_color = gtk_color_button_new ();
  gtk_widget_show (text_color);
  gtk_table_attach (GTK_TABLE (text_colors_table), text_color, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (text_color), FALSE);

  text_background_color = gtk_color_button_new ();
  gtk_widget_show (text_background_color);
  gtk_table_attach (GTK_TABLE (text_colors_table), text_background_color, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (text_background_color), FALSE);

  label84 = gtk_label_new_with_mnemonic (_("Selected text color: "));
  gtk_widget_show (label84);
  gtk_table_attach (GTK_TABLE (text_colors_table), label84, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label84), 0, 0.5);

  label85 = gtk_label_new_with_mnemonic (_("Selection color: "));
  gtk_widget_show (label85);
  gtk_table_attach (GTK_TABLE (text_colors_table), label85, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label85), 0, 0.5);

  selected_text_color = gtk_color_button_new ();
  gtk_widget_show (selected_text_color);
  gtk_table_attach (GTK_TABLE (text_colors_table), selected_text_color, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (selected_text_color), FALSE);

  selection_color = gtk_color_button_new ();
  gtk_widget_show (selection_color);
  gtk_table_attach (GTK_TABLE (text_colors_table), selection_color, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (selection_color), FALSE);

  label81 = gtk_label_new (_("Colors"));
  gtk_widget_show (label81);
  gtk_frame_set_label_widget (GTK_FRAME (frame21), label81);

  frame22 = gtk_frame_new (NULL);
  gtk_widget_show (frame22);
  gtk_box_pack_start (GTK_BOX (vbox15), frame22, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame22), 3);

  alignment32 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (frame22), alignment32);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment32), 0, 3, 3, 3);

  vbox18 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox18);
  gtk_container_add (GTK_CONTAINER (alignment32), vbox18);

  highlight_current_line = gtk_check_button_new_with_mnemonic (_("Highlight current line"));
  gtk_widget_show (highlight_current_line);
  gtk_box_pack_start (GTK_BOX (vbox18), highlight_current_line, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (highlight_current_line), FALSE);

  highlight_current_line_color = gtk_color_button_new ();
  gtk_widget_show (highlight_current_line_color);
  gtk_box_pack_start (GTK_BOX (vbox18), highlight_current_line_color, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (highlight_current_line_color), FALSE);

  label90 = gtk_label_new (_("Current Line"));
  gtk_widget_show (label90);
  gtk_frame_set_label_widget (GTK_FRAME (frame22), label90);

  label61 = gtk_label_new (_("Font and Colors"));
  gtk_widget_show (label61);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 2), label61);

  frame23 = gtk_frame_new (NULL);
  gtk_widget_show (frame23);
  gtk_container_add (GTK_CONTAINER (notebook), frame23);
  gtk_container_set_border_width (GTK_CONTAINER (frame23), 3);

  alignment33 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (frame23), alignment33);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment33), 0, 3, 3, 3);

  syntax_highlighting_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (syntax_highlighting_vbox);
  gtk_container_add (GTK_CONTAINER (alignment33), syntax_highlighting_vbox);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (syntax_highlighting_vbox), hbox7, FALSE, FALSE, 0);

  label93 = gtk_label_new (_("Highlight mode: "));
  gtk_widget_show (label93);
  gtk_box_pack_start (GTK_BOX (hbox7), label93, FALSE, FALSE, 0);

  language_combo = gtk_combo_box_new_text ();
  gtk_widget_show (language_combo);
  gtk_box_pack_start (GTK_BOX (hbox7), language_combo, TRUE, TRUE, 0);

  frame24 = gtk_frame_new (NULL);
  gtk_widget_show (frame24);
  gtk_box_pack_start (GTK_BOX (syntax_highlighting_vbox), frame24, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame24), GTK_SHADOW_NONE);

  alignment34 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (frame24), alignment34);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment34), 6, 0, 3, 3);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox8);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox8), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  styles_list = gtk_tree_view_new ();
  gtk_widget_show (styles_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), styles_list);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (styles_list), FALSE);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (styles_list), FALSE);

  style_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (style_vbox);
  gtk_box_pack_start (GTK_BOX (hbox8), style_vbox, FALSE, TRUE, 0);

  alignment35 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment35);
  gtk_box_pack_start (GTK_BOX (style_vbox), alignment35, FALSE, FALSE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment35), 12, 12, 12, 6);

  hbox9 = gtk_hbox_new (FALSE, 12);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox9);

  bold = gtk_toggle_button_new ();
  gtk_widget_show (bold);
  gtk_box_pack_start (GTK_BOX (hbox9), bold, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (bold), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (bold), FALSE);

  image1 = gtk_image_new_from_stock ("gtk-bold", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (bold), image1);

  italic = gtk_toggle_button_new ();
  gtk_widget_show (italic);
  gtk_box_pack_start (GTK_BOX (hbox9), italic, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (italic), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (italic), FALSE);

  image2 = gtk_image_new_from_stock ("gtk-italic", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (italic), image2);

  underline = gtk_toggle_button_new ();
  gtk_widget_show (underline);
  gtk_box_pack_start (GTK_BOX (hbox9), underline, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (underline), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (underline), FALSE);

  image3 = gtk_image_new_from_stock ("gtk-underline", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (underline), image3);

  strikethrough = gtk_toggle_button_new ();
  gtk_widget_show (strikethrough);
  gtk_box_pack_start (GTK_BOX (hbox9), strikethrough, FALSE, FALSE, 0);
  gtk_button_set_relief (GTK_BUTTON (strikethrough), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (strikethrough), FALSE);

  image4 = gtk_image_new_from_stock ("gtk-strikethrough", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (strikethrough), image4);

  alignment36 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment36);
  gtk_box_pack_start (GTK_BOX (style_vbox), alignment36, FALSE, FALSE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment36), 12, 12, 12, 12);

  table12 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table12);
  gtk_container_add (GTK_CONTAINER (alignment36), table12);
  gtk_table_set_col_spacings (GTK_TABLE (table12), 6);

  foreground_color = gtk_color_button_new ();
  gtk_widget_show (foreground_color);
  gtk_table_attach (GTK_TABLE (table12), foreground_color, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (foreground_color), FALSE);

  background_color = gtk_color_button_new ();
  gtk_widget_show (background_color);
  gtk_table_attach (GTK_TABLE (table12), background_color, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (background_color), FALSE);

  foreground_toggle = gtk_check_button_new_with_mnemonic (_("Foreground: "));
  gtk_widget_show (foreground_toggle);
  gtk_table_attach (GTK_TABLE (table12), foreground_toggle, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (foreground_toggle), FALSE);

  background_toggle = gtk_check_button_new_with_mnemonic (_("Background: "));
  gtk_widget_show (background_toggle);
  gtk_table_attach (GTK_TABLE (table12), background_toggle, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (background_toggle), FALSE);

  use_syntax_highlighting = gtk_check_button_new_with_mnemonic (_("Use Highlighting "));
  gtk_widget_show (use_syntax_highlighting);
  gtk_frame_set_label_widget (GTK_FRAME (frame23), use_syntax_highlighting);
  gtk_tooltips_set_tip (tooltips, use_syntax_highlighting, _("Highlight syntax with colors in editor"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (use_syntax_highlighting), FALSE);

  label92 = gtk_label_new (_("Syntax Highlighting"));
  gtk_widget_show (label92);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 3), label92);

  g_signal_connect ((gpointer) smarthome, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_SMART_HOME_END),
                    NULL);
  g_signal_connect ((gpointer) tabswidth_spin, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_TABS_WIDTH),
                    NULL);
  g_signal_connect ((gpointer) usespaces, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_SPACES_NO_TABS),
                    NULL);
  g_signal_connect ((gpointer) autoindent, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_AUTO_INDENT),
                    NULL);
  g_signal_connect ((gpointer) tab_indents, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_TAB_INDENTS),
                    NULL);
  g_signal_connect ((gpointer) backspace_indents, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BACKSPACE_INDENTS),
                    NULL);
  g_signal_connect ((gpointer) limit_undo, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_LIMIT_UNDO),
                    NULL);
  g_signal_connect ((gpointer) limit_undo_spin, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_LIMIT_UNDO_NUM),
                    NULL);
  g_signal_connect ((gpointer) limit_undo_spin, "moo_sensitive",
                    G_CALLBACK (limit_undo),
                    NULL);
  g_signal_connect ((gpointer) limit_undo_actions_label, "moo_sensitive",
                    G_CALLBACK (limit_undo),
                    NULL);
  g_signal_connect ((gpointer) auto_save, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_AUTO_SAVE),
                    NULL);
  g_signal_connect ((gpointer) auto_save_interval, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_AUTO_SAVE_INTERVAL),
                    NULL);
  g_signal_connect ((gpointer) auto_save_interval, "moo_sensitive",
                    G_CALLBACK (auto_save),
                    NULL);
  g_signal_connect ((gpointer) auto_save_label, "moo_sensitive",
                    G_CALLBACK (auto_save),
                    NULL);
  g_signal_connect ((gpointer) enable_wrapping, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_WRAP_ENABLE),
                    NULL);
  g_signal_connect ((gpointer) dont_split_words, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_WRAP_DONT_SPLIT_WORDS),
                    NULL);
  g_signal_connect ((gpointer) dont_split_words, "moo_sensitive",
                    G_CALLBACK (enable_wrapping),
                    NULL);
  g_signal_connect ((gpointer) show_line_numbers, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_SHOW_LINE_NUMBERS),
                    NULL);
  g_signal_connect ((gpointer) show_right_margin, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_SHOW_MARGIN),
                    NULL);
  g_signal_connect ((gpointer) show_right_margin_spin, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_MARGIN),
                    NULL);
  g_signal_connect ((gpointer) show_right_margin_spin, "moo_sensitive",
                    G_CALLBACK (show_right_margin),
                    NULL);
  g_signal_connect ((gpointer) bracket_styles_notebook, "moo_sensitive",
                    G_CALLBACK (check_brackets),
                    NULL);
  g_signal_connect_swapped ((gpointer) bracket_correct_foreground, "moo_prefs_key",
                            G_CALLBACK (MOO_EDIT_PREFS_BRACKET_CORRECT_MATCH_FOREGROUND),
                            GTK_OBJECT (bracket_correct_use_foreground));
  g_signal_connect_swapped ((gpointer) bracket_correct_background, "moo_prefs_key",
                            G_CALLBACK (MOO_EDIT_PREFS_BRACKET_CORRECT_MATCH_BACKGROUND),
                            GTK_OBJECT (bracket_correct_use_background));
  g_signal_connect ((gpointer) bracket_correct_italic, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_CORRECT_MATCH_ITALIC),
                    NULL);
  g_signal_connect ((gpointer) bracket_correct_strikethrough, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_CORRECT_MATCH_STRIKETHROUGH),
                    NULL);
  g_signal_connect ((gpointer) bracket_correct_underline, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_CORRECT_MATCH_UNDERLINE),
                    NULL);
  g_signal_connect ((gpointer) bracket_correct_bold, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_CORRECT_MATCH_BOLD),
                    NULL);
  g_signal_connect_swapped ((gpointer) bracket_incorrect_foreground, "moo_prefs_key",
                            G_CALLBACK (MOO_EDIT_PREFS_BRACKET_INCORRECT_MATCH_FOREGROUND),
                            GTK_OBJECT (bracket_incorrect_use_foreground));
  g_signal_connect_swapped ((gpointer) bracket_incorrect_background, "moo_prefs_key",
                            G_CALLBACK (MOO_EDIT_PREFS_BRACKET_INCORRECT_MATCH_BACKGROUND),
                            GTK_OBJECT (bracket_incorrect_use_background));
  g_signal_connect ((gpointer) bracket_incorrect_italic, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_INCORRECT_MATCH_ITALIC),
                    NULL);
  g_signal_connect ((gpointer) bracket_incorrect_strikethrough, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_INCORRECT_MATCH_STRIKETHROUGH),
                    NULL);
  g_signal_connect ((gpointer) bracket_incorrect_bold, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_INCORRECT_MATCH_BOLD),
                    NULL);
  g_signal_connect ((gpointer) bracket_incorrect_underline, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BRACKET_INCORRECT_MATCH_UNDERLINE),
                    NULL);
  g_signal_connect ((gpointer) check_brackets, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_CHECK_BRACKETS),
                    NULL);
  g_signal_connect ((gpointer) use_default_font, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_USE_DEFAULT_FONT),
                    NULL);
  g_signal_connect_swapped ((gpointer) font_hbox, "moo_sensitive",
                            G_CALLBACK (use_default_font),
                            GTK_OBJECT (invert));
  g_signal_connect ((gpointer) font, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_FONT),
                    NULL);
  g_signal_connect ((gpointer) use_default_colors, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_USE_DEFAULT_COLORS),
                    NULL);
  g_signal_connect_swapped ((gpointer) text_colors_table, "moo_sensitive",
                            G_CALLBACK (use_default_colors),
                            GTK_OBJECT (invert));
  g_signal_connect ((gpointer) text_color, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_FOREGROUND),
                    NULL);
  g_signal_connect_swapped ((gpointer) text_color, "moo_sensitive",
                            G_CALLBACK (use_default_colors),
                            GTK_OBJECT (invert));
  g_signal_connect ((gpointer) text_background_color, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_BACKGROUND),
                    NULL);
  g_signal_connect_swapped ((gpointer) text_background_color, "moo_sensitive",
                            G_CALLBACK (use_default_colors),
                            GTK_OBJECT (invert));
  g_signal_connect ((gpointer) selected_text_color, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_SELECTED_FOREGROUND),
                    NULL);
  g_signal_connect_swapped ((gpointer) selected_text_color, "moo_sensitive",
                            G_CALLBACK (use_default_colors),
                            GTK_OBJECT (invert));
  g_signal_connect ((gpointer) selection_color, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_SELECTED_BACKGROUND),
                    NULL);
  g_signal_connect_swapped ((gpointer) selection_color, "moo_sensitive",
                            G_CALLBACK (use_default_colors),
                            GTK_OBJECT (invert));
  g_signal_connect ((gpointer) highlight_current_line, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_HIGHLIGHT_CURRENT_LINE),
                    NULL);
  g_signal_connect ((gpointer) highlight_current_line_color, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_HIGHLIGHT_CURRENT_LINE_COLOR),
                    NULL);
  g_signal_connect ((gpointer) highlight_current_line_color, "moo_sensitive",
                    G_CALLBACK (highlight_current_line),
                    NULL);
  g_signal_connect ((gpointer) syntax_highlighting_vbox, "moo_sensitive",
                    G_CALLBACK (use_syntax_highlighting),
                    NULL);
  g_signal_connect ((gpointer) foreground_color, "moo_sensitive",
                    G_CALLBACK (foreground_toggle),
                    NULL);
  g_signal_connect ((gpointer) background_color, "moo_sensitive",
                    G_CALLBACK (background_toggle),
                    NULL);
  g_signal_connect ((gpointer) use_syntax_highlighting, "moo_prefs_key",
                    G_CALLBACK (MOO_EDIT_PREFS_USE_SYNTAX_HIGHLIGHTING),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label82), text_color);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label83), text_background_color);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label84), selected_text_color);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label85), selection_color);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window, window, "window");
  GLADE_HOOKUP_OBJECT (window, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (window, frame15, "frame15");
  GLADE_HOOKUP_OBJECT (window, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (window, smarthome, "smarthome");
  GLADE_HOOKUP_OBJECT (window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window, label32, "label32");
  GLADE_HOOKUP_OBJECT (window, tabswidth_spin, "tabswidth_spin");
  GLADE_HOOKUP_OBJECT (window, usespaces, "usespaces");
  GLADE_HOOKUP_OBJECT (window, label64, "label64");
  GLADE_HOOKUP_OBJECT (window, frame16, "frame16");
  GLADE_HOOKUP_OBJECT (window, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (window, autoindent, "autoindent");
  GLADE_HOOKUP_OBJECT (window, tab_indents, "tab_indents");
  GLADE_HOOKUP_OBJECT (window, backspace_indents, "backspace_indents");
  GLADE_HOOKUP_OBJECT (window, label66, "label66");
  GLADE_HOOKUP_OBJECT (window, frame17, "frame17");
  GLADE_HOOKUP_OBJECT (window, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window, limit_undo, "limit_undo");
  GLADE_HOOKUP_OBJECT (window, limit_undo_spin, "limit_undo_spin");
  GLADE_HOOKUP_OBJECT (window, limit_undo_actions_label, "limit_undo_actions_label");
  GLADE_HOOKUP_OBJECT (window, label67, "label67");
  GLADE_HOOKUP_OBJECT (window, frame25, "frame25");
  GLADE_HOOKUP_OBJECT (window, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (window, vbox19, "vbox19");
  GLADE_HOOKUP_OBJECT (window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window, auto_save, "auto_save");
  GLADE_HOOKUP_OBJECT (window, auto_save_interval, "auto_save_interval");
  GLADE_HOOKUP_OBJECT (window, auto_save_label, "auto_save_label");
  GLADE_HOOKUP_OBJECT (window, label95, "label95");
  GLADE_HOOKUP_OBJECT (window, label21, "label21");
  GLADE_HOOKUP_OBJECT (window, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window, frame18, "frame18");
  GLADE_HOOKUP_OBJECT (window, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (window, enable_wrapping, "enable_wrapping");
  GLADE_HOOKUP_OBJECT (window, dont_split_words, "dont_split_words");
  GLADE_HOOKUP_OBJECT (window, label70, "label70");
  GLADE_HOOKUP_OBJECT (window, frame19, "frame19");
  GLADE_HOOKUP_OBJECT (window, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (window, show_line_numbers, "show_line_numbers");
  GLADE_HOOKUP_OBJECT (window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window, show_right_margin, "show_right_margin");
  GLADE_HOOKUP_OBJECT (window, show_right_margin_spin, "show_right_margin_spin");
  GLADE_HOOKUP_OBJECT (window, label73, "label73");
  GLADE_HOOKUP_OBJECT (window, frame26, "frame26");
  GLADE_HOOKUP_OBJECT (window, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (window, vbox20, "vbox20");
  GLADE_HOOKUP_OBJECT (window, bracket_styles_notebook, "bracket_styles_notebook");
  GLADE_HOOKUP_OBJECT (window, vbox21, "vbox21");
  GLADE_HOOKUP_OBJECT (window, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (window, table13, "table13");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_foreground, "bracket_correct_foreground");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_background, "bracket_correct_background");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_use_foreground, "bracket_correct_use_foreground");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_use_background, "bracket_correct_use_background");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_italic, "bracket_correct_italic");
  GLADE_HOOKUP_OBJECT (window, image6, "image6");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_strikethrough, "bracket_correct_strikethrough");
  GLADE_HOOKUP_OBJECT (window, image8, "image8");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_underline, "bracket_correct_underline");
  GLADE_HOOKUP_OBJECT (window, image7, "image7");
  GLADE_HOOKUP_OBJECT (window, bracket_correct_bold, "bracket_correct_bold");
  GLADE_HOOKUP_OBJECT (window, image_9, "image_9");
  GLADE_HOOKUP_OBJECT (window, label99, "label99");
  GLADE_HOOKUP_OBJECT (window, vbox22, "vbox22");
  GLADE_HOOKUP_OBJECT (window, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (window, table14, "table14");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_foreground, "bracket_incorrect_foreground");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_background, "bracket_incorrect_background");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_use_foreground, "bracket_incorrect_use_foreground");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_use_background, "bracket_incorrect_use_background");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_italic, "bracket_incorrect_italic");
  GLADE_HOOKUP_OBJECT (window, image10, "image10");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_strikethrough, "bracket_incorrect_strikethrough");
  GLADE_HOOKUP_OBJECT (window, image12, "image12");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_bold, "bracket_incorrect_bold");
  GLADE_HOOKUP_OBJECT (window, image9, "image9");
  GLADE_HOOKUP_OBJECT (window, bracket_incorrect_underline, "bracket_incorrect_underline");
  GLADE_HOOKUP_OBJECT (window, image11, "image11");
  GLADE_HOOKUP_OBJECT (window, label100, "label100");
  GLADE_HOOKUP_OBJECT (window, check_brackets, "check_brackets");
  GLADE_HOOKUP_OBJECT (window, label62, "label62");
  GLADE_HOOKUP_OBJECT (window, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (window, frame20, "frame20");
  GLADE_HOOKUP_OBJECT (window, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (window, use_default_font, "use_default_font");
  GLADE_HOOKUP_OBJECT (window, font_hbox, "font_hbox");
  GLADE_HOOKUP_OBJECT (window, label79, "label79");
  GLADE_HOOKUP_OBJECT (window, font, "font");
  GLADE_HOOKUP_OBJECT (window, label78, "label78");
  GLADE_HOOKUP_OBJECT (window, frame21, "frame21");
  GLADE_HOOKUP_OBJECT (window, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (window, use_default_colors, "use_default_colors");
  GLADE_HOOKUP_OBJECT (window, text_colors_table, "text_colors_table");
  GLADE_HOOKUP_OBJECT (window, label82, "label82");
  GLADE_HOOKUP_OBJECT (window, label83, "label83");
  GLADE_HOOKUP_OBJECT (window, text_color, "text_color");
  GLADE_HOOKUP_OBJECT (window, text_background_color, "text_background_color");
  GLADE_HOOKUP_OBJECT (window, label84, "label84");
  GLADE_HOOKUP_OBJECT (window, label85, "label85");
  GLADE_HOOKUP_OBJECT (window, selected_text_color, "selected_text_color");
  GLADE_HOOKUP_OBJECT (window, selection_color, "selection_color");
  GLADE_HOOKUP_OBJECT (window, label81, "label81");
  GLADE_HOOKUP_OBJECT (window, frame22, "frame22");
  GLADE_HOOKUP_OBJECT (window, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (window, highlight_current_line, "highlight_current_line");
  GLADE_HOOKUP_OBJECT (window, highlight_current_line_color, "highlight_current_line_color");
  GLADE_HOOKUP_OBJECT (window, label90, "label90");
  GLADE_HOOKUP_OBJECT (window, label61, "label61");
  GLADE_HOOKUP_OBJECT (window, frame23, "frame23");
  GLADE_HOOKUP_OBJECT (window, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (window, syntax_highlighting_vbox, "syntax_highlighting_vbox");
  GLADE_HOOKUP_OBJECT (window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window, label93, "label93");
  GLADE_HOOKUP_OBJECT (window, language_combo, "language_combo");
  GLADE_HOOKUP_OBJECT (window, frame24, "frame24");
  GLADE_HOOKUP_OBJECT (window, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window, styles_list, "styles_list");
  GLADE_HOOKUP_OBJECT (window, style_vbox, "style_vbox");
  GLADE_HOOKUP_OBJECT (window, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window, bold, "bold");
  GLADE_HOOKUP_OBJECT (window, image1, "image1");
  GLADE_HOOKUP_OBJECT (window, italic, "italic");
  GLADE_HOOKUP_OBJECT (window, image2, "image2");
  GLADE_HOOKUP_OBJECT (window, underline, "underline");
  GLADE_HOOKUP_OBJECT (window, image3, "image3");
  GLADE_HOOKUP_OBJECT (window, strikethrough, "strikethrough");
  GLADE_HOOKUP_OBJECT (window, image4, "image4");
  GLADE_HOOKUP_OBJECT (window, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (window, table12, "table12");
  GLADE_HOOKUP_OBJECT (window, foreground_color, "foreground_color");
  GLADE_HOOKUP_OBJECT (window, background_color, "background_color");
  GLADE_HOOKUP_OBJECT (window, foreground_toggle, "foreground_toggle");
  GLADE_HOOKUP_OBJECT (window, background_toggle, "background_toggle");
  GLADE_HOOKUP_OBJECT (window, use_syntax_highlighting, "use_syntax_highlighting");
  GLADE_HOOKUP_OBJECT (window, label92, "label92");
  GLADE_HOOKUP_OBJECT_NO_REF (window, tooltips, "tooltips");

  return window;
}

