/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "mooeditfind.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog (void)
{
  GtkWidget *dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *vbox2;
  GtkWidget *label3;
  GtkWidget *text_to_find;
  GtkWidget *hbox1;
  GtkWidget *regular_expression;
  GtkWidget *edit;
  GtkWidget *label1;
  GtkWidget *replace_frame;
  GtkWidget *alignment3;
  GtkWidget *vbox3;
  GtkWidget *label4;
  GtkWidget *replacement_text;
  GtkWidget *hbox2;
  GtkWidget *use_placeholders;
  GtkWidget *label5;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *table1;
  GtkWidget *whole_words_only;
  GtkWidget *from_cursor;
  GtkWidget *selected_text;
  GtkWidget *case_sensitive;
  GtkWidget *find_backwards;
  GtkWidget *dont_prompt_on_replace;
  GtkWidget *label2;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancel_btn;
  GtkWidget *ok_btn;

  dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog), _("Find"));
  gtk_window_set_position (GTK_WINDOW (dialog), GTK_WIN_POS_CENTER_ON_PARENT);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (dialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 3);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 6, 6, 6, 6);

  vbox2 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox2);

  label3 = gtk_label_new (_("Text to find:"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox2), label3, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  text_to_find = gtk_entry_new ();
  gtk_widget_show (text_to_find);
  gtk_box_pack_start (GTK_BOX (vbox2), text_to_find, FALSE, FALSE, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (text_to_find), TRUE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, FALSE, 0);

  regular_expression = gtk_check_button_new_with_mnemonic (_("Regular expression  "));
  gtk_widget_show (regular_expression);
  gtk_box_pack_start (GTK_BOX (hbox1), regular_expression, TRUE, TRUE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (regular_expression), FALSE);

  edit = gtk_button_new_with_mnemonic (_("  Edit...  "));
  gtk_box_pack_start (GTK_BOX (hbox1), edit, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (edit), FALSE);

  label1 = gtk_label_new (_("Find"));
  gtk_widget_show (label1);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label1);

  replace_frame = gtk_frame_new (NULL);
  gtk_widget_show (replace_frame);
  gtk_box_pack_start (GTK_BOX (vbox1), replace_frame, FALSE, FALSE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (replace_frame), alignment3);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment3), 6, 6, 6, 6);

  vbox3 = gtk_vbox_new (FALSE, 3);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), vbox3);

  label4 = gtk_label_new (_("Replacement text:"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox3), label4, FALSE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  replacement_text = gtk_entry_new ();
  gtk_widget_show (replacement_text);
  gtk_box_pack_start (GTK_BOX (vbox3), replacement_text, FALSE, FALSE, 0);
  gtk_entry_set_activates_default (GTK_ENTRY (replacement_text), TRUE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox2, FALSE, FALSE, 0);

  use_placeholders = gtk_check_button_new_with_mnemonic (_("Use placeholders  "));
  gtk_widget_show (use_placeholders);
  gtk_box_pack_start (GTK_BOX (hbox2), use_placeholders, TRUE, TRUE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (use_placeholders), FALSE);

  label5 = gtk_label_new (_("Replace With"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (replace_frame), label5);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, FALSE, FALSE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 3, 3, 3, 3);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (alignment2), table1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 3);

  whole_words_only = gtk_check_button_new_with_mnemonic (_("Whole words only"));
  gtk_widget_show (whole_words_only);
  gtk_table_attach (GTK_TABLE (table1), whole_words_only, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (whole_words_only), FALSE);

  from_cursor = gtk_check_button_new_with_mnemonic (_("From cursor"));
  gtk_widget_show (from_cursor);
  gtk_table_attach (GTK_TABLE (table1), from_cursor, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (from_cursor), FALSE);

  selected_text = gtk_check_button_new_with_mnemonic (_("Selected text"));
  gtk_widget_show (selected_text);
  gtk_table_attach (GTK_TABLE (table1), selected_text, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (selected_text), FALSE);

  case_sensitive = gtk_check_button_new_with_mnemonic (_("Case sensitive"));
  gtk_widget_show (case_sensitive);
  gtk_table_attach (GTK_TABLE (table1), case_sensitive, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (case_sensitive), FALSE);

  find_backwards = gtk_check_button_new_with_mnemonic (_("Find backwards"));
  gtk_widget_show (find_backwards);
  gtk_table_attach (GTK_TABLE (table1), find_backwards, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (find_backwards), FALSE);

  dont_prompt_on_replace = gtk_check_button_new_with_mnemonic (_("Don't prompt on replace"));
  gtk_widget_show (dont_prompt_on_replace);
  gtk_table_attach (GTK_TABLE (table1), dont_prompt_on_replace, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (dont_prompt_on_replace), FALSE);

  label2 = gtk_label_new (_("Options"));
  gtk_widget_show (label2);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label2);

  dialog_action_area1 = GTK_DIALOG (dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancel_btn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancel_btn);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), cancel_btn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancel_btn, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (cancel_btn), FALSE);

  ok_btn = gtk_button_new_from_stock ("gtk-find");
  gtk_widget_show (ok_btn);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), ok_btn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (ok_btn, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (ok_btn), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog, "dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (dialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (dialog, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (dialog, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (dialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (dialog, text_to_find, "text_to_find");
  GLADE_HOOKUP_OBJECT (dialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (dialog, regular_expression, "regular_expression");
  GLADE_HOOKUP_OBJECT (dialog, edit, "edit");
  GLADE_HOOKUP_OBJECT (dialog, label1, "label1");
  GLADE_HOOKUP_OBJECT (dialog, replace_frame, "replace_frame");
  GLADE_HOOKUP_OBJECT (dialog, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (dialog, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dialog, label4, "label4");
  GLADE_HOOKUP_OBJECT (dialog, replacement_text, "replacement_text");
  GLADE_HOOKUP_OBJECT (dialog, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (dialog, use_placeholders, "use_placeholders");
  GLADE_HOOKUP_OBJECT (dialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (dialog, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (dialog, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (dialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (dialog, whole_words_only, "whole_words_only");
  GLADE_HOOKUP_OBJECT (dialog, from_cursor, "from_cursor");
  GLADE_HOOKUP_OBJECT (dialog, selected_text, "selected_text");
  GLADE_HOOKUP_OBJECT (dialog, case_sensitive, "case_sensitive");
  GLADE_HOOKUP_OBJECT (dialog, find_backwards, "find_backwards");
  GLADE_HOOKUP_OBJECT (dialog, dont_prompt_on_replace, "dont_prompt_on_replace");
  GLADE_HOOKUP_OBJECT (dialog, label2, "label2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog, cancel_btn, "cancel_btn");
  GLADE_HOOKUP_OBJECT (dialog, ok_btn, "ok_btn");

  gtk_widget_grab_focus (text_to_find);
  gtk_widget_grab_default (ok_btn);
  return dialog;
}

GtkWidget*
create_prompt_on_replace_dialog (void)
{
  GtkWidget *prompt_on_replace_dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *label7;
  GtkWidget *dialog_action_area3;
  GtkWidget *button1;
  GtkWidget *button3;
  GtkWidget *button4;
  GtkWidget *button5;

  prompt_on_replace_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (prompt_on_replace_dialog), _("Replace?"));
  gtk_window_set_type_hint (GTK_WINDOW (prompt_on_replace_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (prompt_on_replace_dialog), FALSE);

  dialog_vbox3 = GTK_DIALOG (prompt_on_replace_dialog)->vbox;
  gtk_widget_show (dialog_vbox3);

  label7 = gtk_label_new (_("Replace?"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), label7, FALSE, FALSE, 0);

  dialog_action_area3 = GTK_DIALOG (prompt_on_replace_dialog)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_with_mnemonic (_("_Replace"));
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (prompt_on_replace_dialog), button1, 3);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (button1), FALSE);

  button3 = gtk_button_new_with_mnemonic (_("Replace _All"));
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (prompt_on_replace_dialog), button3, 4);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (button3), FALSE);

  button4 = gtk_button_new_with_mnemonic (_("Find _Next"));
  gtk_widget_show (button4);
  gtk_dialog_add_action_widget (GTK_DIALOG (prompt_on_replace_dialog), button4, 2);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (button4), FALSE);

  button5 = gtk_button_new_with_mnemonic (_("Sto_p"));
  gtk_widget_show (button5);
  gtk_dialog_add_action_widget (GTK_DIALOG (prompt_on_replace_dialog), button5, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);
  gtk_button_set_focus_on_click (GTK_BUTTON (button5), FALSE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prompt_on_replace_dialog, prompt_on_replace_dialog, "prompt_on_replace_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (prompt_on_replace_dialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (prompt_on_replace_dialog, label7, "label7");
  GLADE_HOOKUP_OBJECT_NO_REF (prompt_on_replace_dialog, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (prompt_on_replace_dialog, button1, "button1");
  GLADE_HOOKUP_OBJECT (prompt_on_replace_dialog, button3, "button3");
  GLADE_HOOKUP_OBJECT (prompt_on_replace_dialog, button4, "button4");
  GLADE_HOOKUP_OBJECT (prompt_on_replace_dialog, button5, "button5");

  gtk_widget_grab_default (button1);
  return prompt_on_replace_dialog;
}

