/* -*- C -*- */
static const char THANKS [] = ""
"To Sveta and Max Muntyan,\n"
"\n"
"and to all who contributed, including\n"
"\n"
"Andreas Hanke\n"
"Andrey Fedoseev\n"
"Arnau Sanchez\n"
"Chaosye\n"
"Christian Dywan\n"
"Collilieux\n"
"Daniel Butzu\n"
"David Hough\n"
"Dmytro Savchuk\n"
"Everaldo Coelho\n"
"Federico Mena Quintero\n"
"Geoffrey French\n"
"Jeroen Zwartepoorte\n"
"Lontronics\n"
"Marco Barisione\n"
"Matthias Clasen\n"
"Nick Treleaven\n"
"Owen Taylor\n"
"Paolo Borelli\n"
"Paolo Maggi\n"
"Philip Hazel\n"
"Scott Wimer\n"
"Thomas Gilgin\n"
"Tim Janik\n"
"Tim-Philipp Müller\n"
"Vlastimil Ott\n"
;
