.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MEDIT 1 "June 20, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
medit \- text editor
.SH SYNOPSIS
.B medit
.RI [ options ]\ [ files ]
.SH DESCRIPTION
.B medit
is a text editor.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of the program.
.TP
.B \-n, \-\-new\-app
Run new instance of \fBmedit\fP. By default \fBmedit\fP opens \fBfiles\fP
in an existing instance of application.
.TP
.B \-s, \-\-use\-session[=yes|no]
Load and save session. By default \fBmedit\fP does it when \-n is not used.
If this option is not given on command line then medit uses the corresponding
preferences setting.
.TP
.B \-\-pid PID
Use existing instance with process id \fBPID\fP.
.TP
.B \-\-app-name NAME
Use instance name \fBNAME\fP. If an instance with this name is already running,
then it will send files given on the command line to that instance and exit.
.TP
.B \-l, \-\-line LINE
Open file and position cursor on line \fBLINE\fP.
.TP
.B \-\-log[=FILE]
Show debug output or write it to \fBFILE\fP.
.TP
.B \-\-debug
Run in debug mode.
.TP
.B \-\-exec STRING
Execute python code in an existing instance.
.TP
.B \-\-exec\-file FILE
Execute python file in an existing instance.
.TP
.B files
List of files to open. Filenames may include line numbers after colon, e.g. /tmp/file.txt:200.
Trailing colon is also fine.
.SH ENVIRONMENT
.TP
.B MEDIT_PID
If set, used as --pid argument. When medit spawns a process (e.g. a DVI viewer) it sets MEDIT_PID
to its own process id, so the child process may in turn simply use 'medit filename' to open a file
(e.g. for inverse DVI search).
.SH CONTACT
http://mooedit.sourceforge.net/contact.html.
.SH AUTHOR
medit was written by Yevgen Muntyan <muntyan@tamu.edu>.
