#
# moo/moopython/plugins/Makefile.incl
#

moopython_pluginsdir = $(MOO_LIB_DIR)/plugins
moopython_plugins_libdir = $(MOO_LIB_DIR)/plugins/lib

moopython_plugins_DATA =                      \
    $(moopython)/plugins/console.py           \
    $(moopython)/plugins/python.py

moopython_plugins_lib_DATA =                  \
    $(moopython)/plugins/pyconsole.py

moo_extra_dist +=                             \
    $(moopython_plugins_DATA)                 \
    $(moopython_plugins_lib_DATA)
