#
# moo/mooutils/pcre/Makefile.incl
#

moopcre = $(mooutils)/pcre

moopcre_sources =                              \
    $(moopcre)/pcre_chartables.c               \
    $(moopcre)/pcre_compile.c                  \
    $(moopcre)/pcre_config.c                   \
    $(moopcre)/pcre_exec.c                     \
    $(moopcre)/pcre_fullinfo.c                 \
    $(moopcre)/pcre_get.c                      \
    $(moopcre)/pcre_globals.c                  \
    $(moopcre)/pcre_info.c                     \
    $(moopcre)/pcre_internal.h                 \
    $(moopcre)/pcre_maketables.c               \
    $(moopcre)/pcre_ord2utf8.c                 \
    $(moopcre)/pcre_refcount.c                 \
    $(moopcre)/pcre_study.c                    \
    $(moopcre)/pcre_tables.c                   \
    $(moopcre)/pcre_try_flipped.c              \
    $(moopcre)/pcre_ucp_findchar.c             \
    $(moopcre)/pcre_valid_utf8.c               \
    $(moopcre)/pcre_version.c                  \
    $(moopcre)/pcre_xclass.c                   \
    $(moopcre)/pcre.h                          \
    $(moopcre)/ucp.h                           \
    $(moopcre)/ucpinternal.h


if MOO_BUILD_PCRE
moo_sources += $(moopcre_sources)
else
moo_extra_dist += $(moopcre_sources)
endif

moo_extra_dist +=                              \
    $(moopcre)/AUTHORS                         \
    $(moopcre)/COPYING.pcre                    \
    $(moopcre)/ChangeLog                       \
    $(moopcre)/NEWS                            \
    $(moopcre)/dftables.c                      \
    $(moopcre)/pcre_printint.src               \
    $(moopcre)/ucptable.c
