#! /bin/sh

# uic-wrapper uic srcdir infiles...

uic="$1"
shift
srcdir="$1"
shift

gen_one() {
  "$uic" -o ui_$1.h.tmp $srcdir/$1.ui || exit 1
  sed 's/\*\* Created: [^*]*$/** Created: today/' ui_$1.h.tmp > ui_$*.h.tmp2 || exit 1
  (cmp -s ui_$1.h.tmp2 ui_$1.h || mv ui_$1.h.tmp2 ui_$1.h) || exit 1
  rm -f ui_$1.h.tmp ui_$1.h.tmp2 || exit 1
}

for arg do
  gen_one $arg
done
