/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* If you are compiling for a system that uses EBCDIC instead of ASCII dnl
   character codes, define this macro as 1. */
#define EBCDIC 0

/* Define to 1 if `TIOCGWINSZ' requires <sys/ioctl.h>. */
/* #undef GWINSZ_IN_SYS_IOCTL */

/* Define to 1 if you have the `bcopy' function. */
/* #undef HAVE_BCOPY */

/* Define to 1 if you have the `cfmakeraw' function. */
/* #undef HAVE_CFMAKERAW */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `getpgid' function. */
/* #undef HAVE_GETPGID */

/* Define to 1 if you have the `getpt' function. */
/* #undef HAVE_GETPT */

/* Define to 1 if you have the `grantpt' function. */
/* #undef HAVE_GRANTPT */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <io.h> header file. */
#define HAVE_IO_H 1

/* Define to 1 if you have the `kill' function. */
/* #undef HAVE_KILL */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if the system has the type `long long'. */
#define HAVE_LONG_LONG 1

/* Define to 1 if you have the `memmove' function. */
#define HAVE_MEMMOVE 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mmap' function. */
/* #undef HAVE_MMAP */

/* Define to 1 if you have the `pipe' function. */
/* #undef HAVE_PIPE */

/* Define to 1 if you have the `poll' function. */
/* #undef HAVE_POLL */

/* Define to 1 if you have the <poll.h> header file. */
/* #undef HAVE_POLL_H */

/* Define to 1 if you have the `posix_openpt' function. */
/* #undef HAVE_POSIX_OPENPT */

/* Define to 1 if you have the `ptsname' function. */
/* #undef HAVE_PTSNAME */

/* Define to 1 if you have the `ptsname_r' function. */
/* #undef HAVE_PTSNAME_R */

/* Define to 1 if you have the `recvmsg' function. */
/* #undef HAVE_RECVMSG */

/* Define to 1 if you have the `signal' function. */
#define HAVE_SIGNAL 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <stropts.h> header file. */
/* #undef HAVE_STROPTS_H */

/* Define to 1 if you have the `strtoll' function. */
#define HAVE_STRTOLL 1

/* Define to 1 if you have the `strtoq' function. */
/* #undef HAVE_STRTOQ */

/* Define to 1 if you have the <sys/select.h> header file. */
/* #undef HAVE_SYS_SELECT_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/termios.h> header file. */
/* #undef HAVE_SYS_TERMIOS_H */

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
/* #undef HAVE_SYS_UN_H */

/* Define to 1 if you have the <sys/utsname.h> header file. */
/* #undef HAVE_SYS_UTSNAME_H */

/* Define to 1 if you have the <sys/wait.h> header file. */
/* #undef HAVE_SYS_WAIT_H */

/* Define to 1 if you have the <termios.h> header file. */
/* #undef HAVE_TERMIOS_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `unlink' function. */
#define HAVE_UNLINK 1

/* Define to 1 if you have the `unlockpt' function. */
/* #undef HAVE_UNLOCKPT */

/* Define to 1 if the system has the type `unsigned long long'. */
#define HAVE_UNSIGNED_LONG_LONG 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define if xmlNode structure has 'line' member */
#define HAVE_XMLNODE_LINE 1

/* Define to 1 if you have the `xmlParseFile' function. */
/* #undef HAVE_XMLPARSEFILE */

/* Define to 1 if you have the `xmlReadFile' function. */
/* #undef HAVE_XMLREADFILE */

/* Define to 1 if you have the `_pipe' function. */
#define HAVE__PIPE 1

/* The value of LINK_SIZE determines the number of bytes used to store dnl
   links as offsets within the compiled regex. The default is 2, which allows
   for dnl compiled patterns up to 64K long. This covers the vast majority of
   cases. dnl However, PCRE can also be compiled to use 3 or 4 bytes instead.
   This allows for dnl longer patterns in extreme cases. */
#define LINK_SIZE 2

/* The value of MATCH_LIMIT determines the default number of times the match()
   dnl function can be called during a single execution of pcre_exec(). (There
   is a dnl runtime method of setting a different limit.) The limit exists in
   order to dnl catch runaway regular expressions that take for ever to
   determine that they do dnl not match. The default is set very large so that
   it does not accidentally catch dnl legitimate cases. */
#define MATCH_LIMIT 10000000

/* build mooapp */
#define MOO_BUILD_APP 

/* build mooedit */
#define MOO_BUILD_EDIT 

/* MOO_BUILD_PCRE - bulid pcre library */
#define MOO_BUILD_PCRE 

/* build mooterm */
/* #undef MOO_BUILD_TERM */

/* build mooutils */
#define MOO_BUILD_UTILS 

/* enable printing */
/* #undef MOO_ENABLE_PRINTING */

/* enable relocation */
#define MOO_ENABLE_RELOCATION 1

/* bsd */
/* #undef MOO_OS_BSD */

/* cygwin */
/* #undef MOO_OS_CYGWIN */

/* darwin */
/* #undef MOO_OS_DARWIN */

/* mingw */
#define MOO_OS_MINGW 1

/* unix */
/* #undef MOO_OS_UNIX */

/* package name */
#define MOO_PACKAGE_NAME "moo"

/* MOO_USE_PYGTK */
/* #undef MOO_USE_PYGTK */

/* MOO_USE_PYTHON */
/* #undef MOO_USE_PYTHON */

/* use xdgmime */
/* #undef MOO_USE_XDGMIME */

/* use libxml */
#define MOO_USE_XML 1

/* "libmoo version" */
#define MOO_VERSION "0.6.999"

/* "libmoo major version" */
#define MOO_VERSION_MAJOR 0

/* "libmoo micro version" */
#define MOO_VERSION_MICRO 999

/* "libmoo minor version" */
#define MOO_VERSION_MINOR 6

/* The value of NEWLINE determines the newline character */
#define NEWLINE '\n'

/* Name of package */
#define PACKAGE "medit"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "muntyan@math.tamu.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "medit"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "medit 0.6.999"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "medit"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.6.999"

/* pcre library release date */
#define PCRE_DATE $PCRE_DATE

/* PCRE_EXPORT - empty since we do not need pcre api be exported */
#define PCRE_EXPORT 

/* pcre library major version */
#define PCRE_MAJOR $PCRE_MAJOR

/* pcre library minor version */
#define PCRE_MINOR $PCRE_MINOR

/* POSIX_MALLOC_THRESHOLD */
#define POSIX_MALLOC_THRESHOLD 10

/* Define as the return type of signal handlers (`int' or `void'). */
#define RETSIGTYPE void

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* SUPPORT_UCP */
#define SUPPORT_UCP 

/* SUPPORT_UTF8 */
#define SUPPORT_UTF8 

/* Version number of package */
#define VERSION "0.6.999"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `int' if <sys/types.h> does not define. */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
