AM_CPPFLAGS += -I$(srcdir)/plugins/support

plugins_sources +=				\
	plugins/support/moocmdview.h		\
	plugins/support/moocmdview.c		\
	plugins/support/mooeditwindowoutput.h	\
	plugins/support/mooeditwindowoutput.c
