SET(moofileview_sources
    moofileview/moofileview.cmake
    moofileview/moobookmarkmgr.cpp
    moofileview/moobookmarkmgr.h
    moofileview/moobookmarkview.cpp
    moofileview/moobookmarkview.h
    moofileview/moofile.cpp
    moofileview/moofile.h
    moofileview/moofile-private.h
    moofileview/moofileentry.cpp
    moofileview/moofileentry.h
    moofileview/moofilesystem.cpp
    moofileview/moofilesystem.h
    moofileview/moofileview.cpp
    moofileview/moofileview.h
    moofileview/moofileview-accels.h
    moofileview/moofileview-aux.h
    moofileview/moofileview-dialogs.cpp
    moofileview/moofileview-dialogs.h
    moofileview/moofileview-impl.h
    moofileview/moofileview-private.h
    moofileview/moofileview-tools.cpp
    moofileview/moofileview-tools.h
    moofileview/moofolder-private.h
    moofileview/moofolder.cpp
    moofileview/moofolder.h
    moofileview/moofoldermodel.cpp
    moofileview/moofoldermodel.h
    moofileview/moofoldermodel-private.h
    moofileview/mooiconview.cpp
    moofileview/mooiconview.h
    moofileview/mootreeview.cpp
    moofileview/mootreeview.h
)

foreach(input_file
    moofileview/glade/moofileview-drop.glade
    moofileview/glade/moofileprops.glade
    moofileview/glade/moocreatefolder.glade
    moofileview/glade/moobookmark-editor.glade
)
    ADD_GXML(${input_file})
endforeach(input_file)

ADD_UI(moofileview/moofileview.xml)
