\input texinfo @c -*-texinfo-*-
@setfilename help.info
@settitle medit 0.99.0-unstable manual
@c %**end of header

@macro medit
medit
@end macro

@macro uilabel{text}
@emph{\text\}
@end macro

@macro helpsection{id}
@html
<!-- moo-help-section: \id\ -->
@end html
@end macro

@titlepage
@title Sample Title
@end titlepage

@contents

@node Top
@top medit

This manual is for medit version 0.99.0-unstable, a text editor.

@menu
* prefs-langs-and-filters:: Selecting editing options and languages.
* Preferences files:: Preferences files.
* Regular expressions:: Regular expressions.
* User-defined Tools:: User-defined Tools.
* Scripting:: Scripting.
* License:: License.
@end menu

@include prefs.texi
@include prefs-file.texi
@include regex.texi
@include user-tools.texi
@include script.texi
@include license.texi

@bye
