@node Scripting
@chapter Scripting
@helpsection{SCRIPT}

@macro method{text}
@code{\text\}
@end macro

@macro param{text}
@code{\text\}
@end macro

@menu
* Lua:: Lua
* Python:: Python
@end menu

@node Lua
@section Lua
@include script-lua.texi

@node Python
@section Python
@include script-python.texi
