#! /bin/sh

# moc-wrapper moc srcdir output infiles...

moc="$1"
shift
srcdir="$1"
shift
output="$1"
shift

cat_args=
moc_args=
for arg do
  cat_args="$cat_args $srcdir/$arg"
  moc_args="$moc_args -f$arg"
done

(cat $cat_args | $moc $moc_args -o $output.tmp) || exit 1
(sed 's/\*\* Created: [^*]*$/** Created: today/' $output.tmp > $output.tmp2) || exit 1
(cmp -s $output.tmp2 $output || mv $output.tmp2 $output) || exit 1
rm -f $output.tmp $output.tmp2
