#! /bin/sh

builddir=`pwd`
srcdir=`dirname $0`/../..
srcdir=`cd $srcdir && pwd`
if [ ! -e $srcdir/configure ]; then
  echo "configure script not found"
  exit 1
fi

_mingw_tool_prefix='/usr/bin/i586-mingw32msvc'

export mgwdir=`dirname $0`/gtk-win
. $mgwdir/config.sh || exit 1

if [ "$mgwconfig" = "debug" ]; then
  _def_cflags='-gstabs'
else
  _def_cflags='-O2'
fi

export ADDR2LINE=$_mingw_tool_prefix-addr2line
export AS=$_mingw_tool_prefix-as
export CC=$_mingw_tool_prefix-gcc
export CPP=$_mingw_tool_prefix-cpp
export CPPFILT=$_mingw_tool_prefix-c++filt
export CXX=$_mingw_tool_prefix-g++
export DLLTOOL=$_mingw_tool_prefix-dlltool
export DLLWRAP=$_mingw_tool_prefix-dllwrap
export GCOV=$_mingw_tool_prefix-gcov
export LD=$_mingw_tool_prefix-ld
export NM=$_mingw_tool_prefix-nm
export OBJCOPY=$_mingw_tool_prefix-objcopy
export OBJDUMP=$_mingw_tool_prefix-objdump
export READELF=$_mingw_tool_prefix-readelf
export SIZE=$_mingw_tool_prefix-size
export STRINGS=$_mingw_tool_prefix-strings
export WINDRES=$_mingw_tool_prefix-windres
export RC=$_mingw_tool_prefix-windres
export AR=$_mingw_tool_prefix-ar
export RANLIB=$_mingw_tool_prefix-ranlib
export STRIP=$_mingw_tool_prefix-strip

export LDFLAGS="-L$mgwtargetdir/lib"
export CPPFLAGS="-I$mgwtargetdir/include"
export CFLAGS="-mms-bitfields -march=i686 $_def_cflags"
export CXXFLAGS="-mms-bitfields -march=i686 $_def_cflags"
export OBJCFLAGS="-mms-bitfields -march=i686 $_def_cflags"

export PKG_CONFIG_LIBDIR="$mgwtargetdir/lib/pkgconfig"
export PKG_CONFIG_PATH="$mgwtargetdir/lib/pkgconfig"

export INSTALL=install-check

configure_args="--build=i686-pc-linux-gnu --host=i586-pc-mingw32msvc --target=i586-pc-mingw32msvc \
AR=$AR RANLIB=$RANLIB STRIP=$STRIP AS=$AS DLLTOOL=$DLLTOOL OBJDUMP=$OBJDUMP NM=$NM WINDRES=$WINDRES RC=$RC \
--prefix=$mgwtargetdir --enable-silent-rules"

if [ "$mgwconfig" = "debug" ]; then
  moo_configure_args='--enable-debug'
else
  moo_configure_args='--enable-dev-mode'
fi

echo $srcdir/configure $configure_args $moo_configure_args "$@"
exec $srcdir/configure $configure_args $moo_configure_args "$@"
