#
# moo/Makefile.incl
#

moo_sources =
moo_win32_sources =
moo_unix_sources =
moo_built_sources =
moo_nodist_sources =
moo_noinst_programs =
moo_cleanfiles =

moo_extra_dist =          \
    $(moo_prefix)/moo.h   \
    $(moo_prefix)/TODO
