#
# moo/Makefile.incl
#

moo_sources =
moo_win32_sources =
moo_unix_sources =
moo_built_sources =
moo_nodist_sources =
moo_cleanfiles =

moo_include_headers =               \
    $(moo_prefix)/moo.h

moo_libinclude_headers =            \
    $(moo_prefix)/moo-config.h

moo_extra_dist =                    \
    $(moo_prefix)/moo.h             \
    $(moo_prefix)/TODO
