#!/bin/sh
set -e

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac

if [ -x "`which gtk-update-icon-cache 2>/dev/null`" ]; then
    gtk-update-icon-cache /usr/share/icons/hicolor
fi

#DEBHELPER#
