moo_sources +=				\
	moocpp/gobjectutils.h		\
	moocpp/gobjptr.cpp		\
	moocpp/gobjptr.h		\
	moocpp/gobjptrtypes.h		\
	moocpp/gobjptrtypes-gio.cpp	\
	moocpp/gobjptrtypes-gio.h	\
	moocpp/gobjptrtypes-glib.cpp	\
	moocpp/gobjptrtypes-glib.h	\
	moocpp/gobjptrtypes-gtk.cpp	\
	moocpp/gobjptrtypes-gtk.h	\
	moocpp/grefptr.cpp		\
	moocpp/grefptr.h		\
	moocpp/memutils.h		\
	moocpp/strutils.cpp		\
	moocpp/strutils.h		\
	moocpp/utils.h

# -%- use-tabs:true, indent-width: 8, strip:true -%-
