SET(moocpp_sources
	moocpp/moocpp.cmake
	moocpp/gobjectutils.h
	moocpp/gobjptr.h
	moocpp/gobjptr.cpp
	moocpp/grefptr.h
	moocpp/grefptr.cpp
	moocpp/memutils.h
	moocpp/strutils.h
	moocpp/strutils.cpp
	moocpp/utils.h
)
