SET(moocpp_sources
	moocpp/moocpp.cmake
	moocpp/gobjectutils.h
	moocpp/gobjectptr.h
	moocpp/gobjectptr.cpp
	moocpp/gobjectprivate.h
	moocpp/gobjectprivate.cpp
	moocpp/memutils.h
	moocpp/strutils.h
	moocpp/strutils.cpp
	moocpp/utils.h
)
