#!/bin/sh

GETTEXT_PACKAGE=medit-1

case `pwd` in
  */po-gsv)
    GETTEXT_PACKAGE=medit-1-gsv
    ;;
esac

do_or_die() {
  echo "$*"
  "$@" || exit 1
}

for f in pot dist; do if [ ! -e $f ]; then ln -s maintain $f; fi; done

dist () {
  if [ -n "$1" ]; then
    echo "intltool-update --gettext-package=$GETTEXT_PACKAGE -d $*"
    exec intltool-update --gettext-package=$GETTEXT_PACKAGE -d "$@"
  fi

  for f in *.po; do
    do_or_die intltool-update --gettext-package=$GETTEXT_PACKAGE -d `basename $f .po`
  done

  exit 0
}

case `basename $0` in
  pot)
    args="--gettext-package=$GETTEXT_PACKAGE -p"
    ;;
  dist)
    dist "$@"
    ;;
  *)
    args="--gettext-package=$GETTEXT_PACKAGE -m"
    ;;
esac

echo "intltool-update $args $*"
exec intltool-update $args "$@"
