dist/mac/Info.plist: dist/mac/Info.plist.in
	$(SHELL) ./config.status --file=dist/mac/Info.plist && mv dist/mac/Info.plist $(srcdir)/dist/mac/

mac-bundle: dist/mac/Info.plist
	ige-mac-bundler $(srcdir)/dist/mac/medit.bundle

mac-clean:
	rm -f $(srcdir)/dist/mac/dist/mac/Info.plist

EXTRA_DIST +=				\
	dist/mac/medit.bundle		\
	dist/mac/Info.plist.in		\
	dist/mac/gtkrc			\
	dist/mac/medit.icns		\
	dist/mac/environment.sh
