SET(glib_2_16_sources
  glib/gurifuncs.c
  glib/gurifuncs.h
  gio/gappinfo.c
  gio/gappinfo.h
  gio/gasynchelper.c
  gio/gasynchelper.h
  gio/gasyncresult.c
  gio/gasyncresult.h
  gio/gbufferedinputstream.c
  gio/gbufferedinputstream.h
  gio/gbufferedoutputstream.c
  gio/gbufferedoutputstream.h
  gio/gcancellable.c
  gio/gcancellable.h
  gio/gcontenttype.c
  gio/gcontenttype.h
  gio/gcontenttypeprivate.h
  gio/gdatainputstream.c
  gio/gdatainputstream.h
  gio/gdataoutputstream.c
  gio/gdataoutputstream.h
  gio/gdesktopappinfo.c
  gio/gdesktopappinfo.h
  gio/gdrive.c
  gio/gdrive.h
  gio/gdummyfile.c
  gio/gdummyfile.h
  gio/gemblem.c
  gio/gemblemedicon.c
  gio/gemblemedicon.h
  gio/gemblem.h
  gio/gfileattribute.c
  gio/gfileattribute.h
  gio/gfileattribute-priv.h
  gio/gfile.c
  gio/gfileenumerator.c
  gio/gfileenumerator.h
  gio/gfile.h
  gio/gfileicon.c
  gio/gfileicon.h
  gio/gfileinfo.c
  gio/gfileinfo.h
  gio/gfileinputstream.c
  gio/gfileinputstream.h
  gio/gfilemonitor.c
  gio/gfilemonitor.h
  gio/gfileoutputstream.c
  gio/gfileoutputstream.h
  gio/gfilterinputstream.c
  gio/gfilterinputstream.h
  gio/gfilteroutputstream.c
  gio/gfilteroutputstream.h
  gio/gicon.c
  gio/gicon.h
  gio/ginputstream.c
  gio/ginputstream.h
  gio/gioaliasdef.c
  gio/gioalias.h
  gio/gioenums.h
  gio/gioenumtypes.c
  gio/gioenumtypes.h
  gio/gioerror.c
  gio/gioerror.h
  gio/gio.h
  gio/gio-marshal.c
  gio/gio-marshal.h
  gio/giomodule.c
  gio/giomodule.h
  gio/giomodule-priv.h
  gio/gioscheduler.c
  gio/gioscheduler.h
  gio/giotypes.h
  gio/glibintl.h
  gio/gloadableicon.c
  gio/gloadableicon.h
  gio/glocaldirectorymonitor.c
  gio/glocaldirectorymonitor.h
  gio/glocalfile.c
  gio/glocalfileenumerator.c
  gio/glocalfileenumerator.h
  gio/glocalfile.h
  gio/glocalfileinfo.c
  gio/glocalfileinfo.h
  gio/glocalfileinputstream.c
  gio/glocalfileinputstream.h
  gio/glocalfilemonitor.c
  gio/glocalfilemonitor.h
  gio/glocalfileoutputstream.c
  gio/glocalfileoutputstream.h
  gio/glocalvfs.c
  gio/glocalvfs.h
  gio/gmemoryinputstream.c
  gio/gmemoryinputstream.h
  gio/gmemoryoutputstream.c
  gio/gmemoryoutputstream.h
  gio/gmount.c
  gio/gmount.h
  gio/gmountoperation.c
  gio/gmountoperation.h
  gio/gmountprivate.h
  gio/gnativevolumemonitor.c
  gio/gnativevolumemonitor.h
  gio/goutputstream.c
  gio/goutputstream.h
  gio/gpollfilemonitor.c
  gio/gpollfilemonitor.h
  gio/gseekable.c
  gio/gseekable.h
  gio/gsimpleasyncresult.c
  gio/gsimpleasyncresult.h
  gio/gthemedicon.c
  gio/gthemedicon.h
  gio/gunionvolumemonitor.c
  gio/gunionvolumemonitor.h
  gio/gunixinputstream.c
  gio/gunixinputstream.h
  gio/gunixmount.c
  gio/gunixmount.h
  gio/gunixmounts.c
  gio/gunixmounts.h
  gio/gunixoutputstream.c
  gio/gunixoutputstream.h
  gio/gunixvolume.c
  gio/gunixvolume.h
  gio/gunixvolumemonitor.c
  gio/gunixvolumemonitor.h
  gio/gvfs.c
  gio/gvfs.h
  gio/gvolume.c
  gio/gvolume.h
  gio/gvolumemonitor.c
  gio/gvolumemonitor.h
)

FOREACH(_moo_f ${glib_2_16_sources})
  LIST(APPEND MOOUTILS_SOURCES newgtk/glib-2.16/${_moo_f})
ENDFOREACH(_moo_f)
LIST(APPEND MOO_DEP_LIBS "rt")
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR}/mooutils/newgtk/glib-2.16/gio)
ADD_DEFINITIONS(-DGIO_COMPILATION -DGIO_MODULE_DIR=\"///nonexistent\")

# -%- strip:true -%-
