mooui_sources =				\
	mooappabout.c			\
	mooappabout.h			\
	mooapp.c			\
	mooapp.h			\
	mooapp-private.h		\
	mooapp-accels.h			\
	moohtml.h			\
	moohtml.c			\
	moolinklabel.h			\
	moolinklabel.c

noinst_LTLIBRARIES = libmooui.la
libmooui_la_SOURCES = $(mooui_sources)
libmooui_la_LIBADD = libsmclient.la

GLADE_FILES = glade/mooappabout.glade

AM_CFLAGS =			\
	$(MOO_CFLAGS)		\
	$(MOO_DEBUG_CFLAGS)

include ../../mk/marshals.mk
include smclient/Makefile.incl
