#!/bin/sh

for f in pot dist; do if test ! -e $f; then ln -s maintain $f; fi; done

case `basename $0` in
    pot)
        args="--gettext-package=moo-gsv -p"
        ;;
    dist)
        args="--gettext-package=moo-gsv -d"
        ;;
    *)
        args="--gettext-package=moo-gsv -m"
        ;;
esac

exec intltool-update $args $*
