#
# moo/moopython/Makefile.incl
#

moopython = $(moo_prefix)/moopython
moopython_srcdir = $(srcdir)/$(moopython)

moopython_sources =                             \
    $(moopython)/moopython-utils.c              \
    $(moopython)/moopython-utils.h

if MOO_BUILD_EDIT
moopython_sources +=                            \
    $(moopython)/mooplugin-python.c             \
    $(moopython)/mooplugin-python.h
endif

moopython_built_sources =
moopython_nodist_sources =
moopython_cleanfiles =
