#
# moo/moopython/Makefile.incl
#

moopython = $(moo_prefix)/moopython
moopython_srcdir = $(srcdir)/$(moopython)

moopython_sources =                             \
    $(moopython)/moopython-utils.c              \
    $(moopython)/moopython-utils.h              \
    $(moopython)/mooplugin-python.c             \
    $(moopython)/mooplugin-python.h

if MOO_USE_PYGTK
moo_sources += $(moopython_sources)
endif
