#
# moo/mooutils/glade/Makefile.incl
#

mooutils_glade = $(mooutils)/glade

moo_extra_dist +=                             \
    $(mooutils_glade)/accelbutton.glade       \
    $(mooutils_glade)/accelprefs.glade        \
    $(mooutils_glade)/moologwindow.glade
