/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "shortcutdialog.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog (void)
{
  GtkWidget *dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *eventbox;
  GtkWidget *frame1;
  GtkWidget *alignment31;
  GtkWidget *label;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancel;
  GtkWidget *alignment29;
  GtkWidget *hbox11;
  GtkWidget *image1;
  GtkWidget *label65;
  GtkWidget *ok;
  GtkWidget *alignment30;
  GtkWidget *hbox12;
  GtkWidget *image2;
  GtkWidget *label66;

  dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog), _("Choose Accelerator"));
  gtk_window_set_type_hint (GTK_WINDOW (dialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (dialog), FALSE);

  dialog_vbox1 = GTK_DIALOG (dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  eventbox = gtk_event_box_new ();
  gtk_widget_show (eventbox);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), eventbox, TRUE, TRUE, 0);
  GTK_WIDGET_SET_FLAGS (eventbox, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (eventbox, GTK_CAN_DEFAULT);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (eventbox), frame1);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 6);

  alignment31 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (frame1), alignment31);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment31), 6, 6, 6, 6);

  label = gtk_label_new (_("\nNew accelerator...\n"));
  gtk_widget_show (label);
  gtk_container_add (GTK_CONTAINER (alignment31), label);

  dialog_action_area1 = GTK_DIALOG (dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancel = gtk_button_new ();
  gtk_widget_show (cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_UNSET_FLAGS (cancel, GTK_CAN_FOCUS);
  gtk_button_set_focus_on_click (GTK_BUTTON (cancel), FALSE);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (cancel), alignment29);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox11);

  image1 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox11), image1, FALSE, FALSE, 0);

  label65 = gtk_label_new_with_mnemonic ("Cancel");
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox11), label65, FALSE, FALSE, 0);

  ok = gtk_button_new ();
  gtk_widget_show (ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog), ok, GTK_RESPONSE_OK);
  GTK_WIDGET_UNSET_FLAGS (ok, GTK_CAN_FOCUS);
  gtk_button_set_focus_on_click (GTK_BUTTON (ok), FALSE);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (ok), alignment30);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox12);

  image2 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox12), image2, FALSE, FALSE, 0);

  label66 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox12), label66, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog, "dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog, eventbox, "eventbox");
  GLADE_HOOKUP_OBJECT (dialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (dialog, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (dialog, label, "label");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog, cancel, "cancel");
  GLADE_HOOKUP_OBJECT (dialog, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (dialog, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (dialog, image1, "image1");
  GLADE_HOOKUP_OBJECT (dialog, label65, "label65");
  GLADE_HOOKUP_OBJECT (dialog, ok, "ok");
  GLADE_HOOKUP_OBJECT (dialog, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (dialog, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (dialog, image2, "image2");
  GLADE_HOOKUP_OBJECT (dialog, label66, "label66");

  gtk_widget_grab_focus (eventbox);
  gtk_widget_grab_default (eventbox);
  return dialog;
}

