if [ ! -z $1 ]; then
    if [ ! -e $1 ]; then
        echo $0: error, file $1 doesn\'t exist
        exit 1
    fi
fi

macros () {
cat <<EOF
#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (PACKAGE, String)
#  define Q_(String) g_strip_context ((String), gettext (String))
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define Q_(String) g_strip_context ((String), (String))
#  define N_(String) (String)
#endif

EOF
}


macros
cat $1 | sed -e 's/#include "support.h"//' | \
         sed -e ':a' -e '$!N;s/\/\*\n \* DO NOT EDIT THIS FILE - it is generated by Glade\./DONOTEDITTHISFILE/;ta' -e 'P;D' | \
         sed -e ':a' -e '$!N;s/DONOTEDITTHISFILE\n \*\///;ta' -e 'P;D' | \
         sed -e 's/#ifdef HAVE_CONFIG_H//' | \
         sed -e ':a' -e '$!N;s/#  include <config.h>\n#endif//;ta' -e 'P;D' | \
         sed -e ':a' -e '$!N;s/,\n[ \t]*\(.*$\)/, \1/;ta' -e 'P;D' | \
         sed '/./,/^$/!d'

